### ISSUE TITLE
Как подключить больше одного устройства Sonoff mini?

### ISSUE THREAD

**Issue by drdic** [AlexxIT/SonoffLAN#1]
Здравствуйте! Подключил по вашему методу устройство Sonoff mini. Встроил его в настольную лампу. Все работает отлично. Можно ли подключить больше одного устройства? Перепробовал много вариантов:
sonoff:
    - devices:
      1000a44d9a:
          apikey: !secret sonoff_mini_1_apikey
          channels: 1
    - devices:
      1000a561bf:
        apikey: !secret sonoff_mini_2_apikey
        channels: 2
И так:
sonoff:
   devices:
       - 1000a44d9a:
              apikey: !secret sonoff_mini_1_apikey
              channels: 1
      - 1000a561bf:
              apikey: !secret sonoff_mini_2_apikey
              channels: 2
Всё равно не работает. Помогите.

**Comment by AlexxIT** [comment]
@drdic Там не список, а словарь
```yaml
sonoff:
  devices:
    1000abcdef:
      apikey: aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee
      channels: 2
    1000abcdef:
      apikey: aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee
      channels: 2
```
Сейчас я тестирую новую версию, которая скачивает список устройств с китайских серверов. Больше не нужно узнавать ключи устройств самостоятельно. И ещё есть ряд плюшек. Если не будет багов - скоро выложу.
