### ISSUE TITLE
Setting one channel in a scene flips all channels in a 4-gang eWeLink light switch

### ISSUE THREAD

**Issue by koskila** [AlexxIT/SonoffLAN#1029]
Hi folks,

I've got an interesting issue whenever I set up automations with my eWeLink -compatible 4-gang lights. Long story short, when an automation/scene sets one channel (entity) to off or on, the device sets all channels to that value (once). It only happens on first call - if the same automation then proceeds to set a channel to something else, only that channel is seemingly effected.

This is driving my wife nuts. And while it's funny, it's also a bit annoying.

Anyway, here's everything relevant in my configuration - any thoughts?

Scene YAML:
```
- id: '1666810172107'
  name: Outdoor lights off
  entities:
    switch.sonoff_10013cc2c0:
      friendly_name: socket_outdoor_shed1
      state: 'off'
    switch.sonoff_a480027885_2:
      friendly_name: Channel2_outdoor
      state: 'off'
  icon: mdi:string-lights-off
  metadata:
    switch.sonoff_a480027885_2:
      entity_only: true
```

Automation YAML:
```
alias: Lights outdoors at sunrise
description: ""
trigger:
  - platform: sun
    event: sunrise
    offset: "-5"
condition: []
action:
  - service: scene.turn_on
    target:
      entity_id: scene.lights_outdoors_at_sunrise
    metadata: {}
mode: single
```
(as a side note, I don't know why the scene ids don't match - it seems to call the light scene, though. It's created through the UI)

And here's the device:
![image](https://user-images.githubusercontent.com/4086860/201191099-b0c46112-ac6c-4fee-af19-47f048682b51.png)

And this is what it looks like when the automation turns outdoor lights - channel_2 - off. And also all the other ones.
![image](https://user-images.githubusercontent.com/4086860/201191699-38be04dc-5934-425f-813d-01efe9fac1c9.png)

And here's what it looks like in the logbook:
![image](https://user-images.githubusercontent.com/4086860/201191883-d03675e5-4bf2-408e-bd2c-c84c4915de1c.png)

There were some errors in the logs about cloud connectivity - but those were hours apart from the actual error.

Oh, and when I create automations using the eWeLink app, it seems to work without similar issues. But I'd prefer to have everything in Home Assistant if possible :)

Any thoughts?
