### ISSUE TITLE
Question:  How to add multiple th16 temperature sensors

### ISSUE THREAD

**Issue by Vards0** [AlexxIT/SonoffLAN#107]
Hi.

I have multiple th16 temperature devices.

Please advise how I can add more than 1 to the configuration.yaml file.

Home Assistant always detects the last one but none of the previous entries.

My config:-

sensor:
- platform: template
  sensors:
    temperature_th:
      friendly_name: Boiler Temperature
      device_class: temperature
      value_template: "{{ state_attr('switch.sonoff_1000bd0443', 'temperature') }}"
  
sensor:
- platform: template
  sensors:
    temperature_th1:
      friendly_name: Boiler 2 Temperature
      device_class: temperature
      value_template: "{{ state_attr('switch.sonoff_10007be89e', 'temperature') }}"

Only Boiler 2 is picked up as a sensor.

Thanks

**Comment by AlexxIT** [comment]
```
sensor:
- platform: template
  sensors:
    temperature_th:
      friendly_name: Boiler Temperature
      device_class: temperature
      value_template: "{{ state_attr('switch.sonoff_1000bd0443', 'temperature') }}"
    temperature_th1:
      friendly_name: Boiler 2 Temperature
      device_class: temperature
      value_template: "{{ state_attr('switch.sonoff_10007be89e', 'temperature') }}"
```
