### ISSUE TITLE
Entity state “unavailable” not usable

### ISSUE THREAD

**Issue by GGSSDD** [AlexxIT/SonoffLAN#1079]
I’m trying to make an automation for a Sonoff S26 plug, to notify when me when I have a power outage, using the “unavailable” state, but that doesn’t seem to work at all. I can only use “on” and “off”… it seems that these are the only states that could make the automation responsive, but unfortunately “off” doesn’t really help, considering the fact that the entity itself is still available.

Thank you.

**Comment by AlexxIT** [comment]
You need to:
- checks errors in Hass logs
- download integration diagnostics
- collect debug logs

**Comment by heidricha** [comment]
I use automation to notify me when device state goes unavailable. Works fine for me...

It is true, that my device stays on, doesn't loose mains, only the integration changes the state to unavailable.

```
alias: Sonoff leszakadt
description: ""
trigger:
  - platform: state
    entity_id:
      - switch.sonoff_10015aae9b_led
    to: unavailable
    for:
      hours: 0
      minutes: 5
      seconds: 0
  - platform: state
    entity_id:
      - switch.sonoff_10015bc32f_led
    to: unavailable
condition: []
action:
  - service: notify.telegram_text
    data:
      message: Sonoff leszakadt gondolom
mode: restart
```
