### ISSUE TITLE
Custom spec doesn't update set_state callback

### ISSUE THREAD

**Issue by dguihal** [AlexxIT/SonoffLAN#1163]
Following https://github.com/AlexxIT/SonoffLAN/pull/1109 I'm facing a status update on dualfan setup

Looks like the XCoverDualR3 set_state function is stilled called even if the entity override is set

```
sonoff:
  devices:
    100xxxxxxxx:
      device_class: dualfan
      name: VMC
```

I'm trying to get why it isn't updated (maybe it it isn't for any override but have any other consequences on other entities)

@AlexxIT do you have any clues on this ?
