### ISSUE TITLE
Sonoff POW template configuration

### ISSUE THREAD

**Issue by KixMan28** [AlexxIT/SonoffLAN#12]
Hi Alex! Could you please post  Sonoff POW template-sensor configuration, similar to the temp-humidity sample? I tried to modify the one for the TH sensor, but it doesn't work.
   ` 
   pow_nas_power:
      friendly_name: Sonoff POW NAS Power
      device_class: power
      value_template: "{{ state_attr('switch.sonoff_10000bb678', 'power') }}"
    pow_multim_power:
      friendly_name: Sonoff POW MM Power
      entity_id: switch.sonoff_100012f43f
      value_template: "{{ state_attr('switch.sonoff_100012f43f', 'power') }}"
`

**Comment by AlexxIT** [comment]
I think something like this:
```
sensor:
- platform: template
  sensors:
    pow_nas_power:
      friendly_name: Sonoff POW NAS Power
      device_class: power
      value_template: "{{ state_attr('switch.sonoff_10000bb678', 'power') }}"
    pow_multim_power:
      friendly_name: Sonoff POW MM Power
      device_class: power
      value_template: "{{ state_attr('switch.sonoff_100012f43f', 'power') }}"
```
