### ISSUE TITLE
Sonoff ZBMINI switch toggles to previous state after being pressed on HA dashboard.

### ISSUE THREAD

**Issue by javbot** [AlexxIT/SonoffLAN#1231]
Sonoff ZBMINI switch toggles to previous state after bring pressed on HA dashboard.

e.g.
1) Initial state of ZB Switch is ON.
2) Switch OFF from Dashboard (actual switch turns OFF, ewelink app changed from ON to OFF).
3) After about one second, turns ON on HA DASHBOARD, however actual switch is still OFF (ewelink app also still OFF)
Outcome: Dashboard state out-of-sync with actual switch

The same but inverse applies if initial state if OFF. Disabled all automations to make sure nothing is messing up. When toggling the switch from ewelink app, the state is updated correctly in HA.

UPDATE:

The following three lines are logged when turning the switch ON.
```
[custom_components.sonoff.core.ewelink.local] <zbbridge_id> => Local4 | 192.168.1.10:8081 | {'switch': 'on', 'subDevId': '<zbswitch_id>'} <= {'sequence': '1698038403002', 'seq': 2, 'error': 400, 'encrypt': True}
[custom_components.sonoff.core.ewelink.cloud] <zbswitch_id> => Cloud4 | {'switch': 'on'} | 1698038403002
[custom_components.sonoff.core.ewelink.cloud] <zbswitch_id> => Cloud4 | 1698038403003
```
No extra lines are logged when the switch toggles back to OFF.

UPDATE 2:

After some debugging, I can confirm that XSwitch methods set_state, async_turn_on and async_turn_off are NOT being called in Step 3 above.

**Comment by javbot** [comment]
I get the following warning when using the ZBMINI switch:

 WARNING (MainThread) [custom_components.sonoff.core.ewelink.cloud] Cloud ERROR: {'error': 411, ......

**Comment by javbot** [comment]
configuration.yaml:

```
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

recorder:
  db_url:  mysql://hass-user:XXXXXXXX@172.18.0.2:3306/hass-db?charset=utf8mb4
  purge_keep_days: 365

sonoff:
  username: !secret sonoff_user
  password: !secret sonoff_cloud_password
  force_update: [temperature, humidity, power]
  scan_interval: '00:05:00' # (optional) default 5 minutes
  sensors: [temperature, humidity, power]
  mode: cloud
  reload: always  # update device list every time HA starts

http:
  ssl_certificate: dehydrated/certs/XXXXXXXX.duckdns.org/fullchain.pem
  ssl_key: dehydrated/certs/XXXXXXXX.duckdns.org/privkey.pem
```
