### ISSUE TITLE
Power and Current not updated for POW devices

### ISSUE THREAD

**Issue by Vards0** [AlexxIT/SonoffLAN#125]
Hi Alexx

I cannot seem to get the current power usage (W) from my POWR2 device after it is switched on.  The guage remains at 0.  

I presume this is either due to an incorrect configuration or has something to do with the refresh process.

My configuration.yaml settings for it are as follows:-

```
sonoff:
  username: !secret
  password: !secret
  mode: local
  reload: always
  scan_interval: 00:01:00  
  devices:
     switch.sonoff_10009xxxxx:
      name: POWR2
      force_update: True

sensor:
- platform: template
  sensors:
      power_pow:
      friendly_name: POWR2 Power Usage
      device_class: power
      value_template: "{{ state_attr('switch.sonoff_10009xxxxx', 'power') }}"
```

Any ideas?  I have the same config in place for a TH16 temperature sensor and that works perfectly.

Thanks
