### ISSUE TITLE
SNZB-02P battery information is not displayed after update

### ISSUE THREAD

**Issue by a1ex-ak** [AlexxIT/SonoffLAN#1349]
```yaml
"home_assistant": {
    "installation_type": "Home Assistant Supervised",
    "version": "2024.2.2",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.12.1",
    "docker": true,
    "arch": "aarch64",
    "os_name": "Linux",
    "os_version": "6.6.16-v8+",
    "supervisor": "2024.01.1",
    "host_os": "Debian GNU/Linux 12 (bookworm)",
    "docker_version": "25.0.2",
    "chassis": "",
    "run_as_root": true
```
```yaml
"model": "SNZB-02P",
        "online": true,
        "local": null,
        "localtype": null,
        "host": null
      },
      "a4800764ed": {
        "uiid": 1771,
        "params": {
          "bindInfos": "***",
          "subDevId": "113477feff96ab901771",
          "parentid": "10010954d7",
          "fwVersion": "1.0.9",
          "tempComfortUpper": "3000",
          "humiComfortUpper": "6000",
          "temperature": "2370",
          "tempComfortStatus": 0,
          "humidity": "3920",
          "humiComfortStatus": 1,
          "timeZone": 3,
          "tempUnit": 0,
          "battery": 100,
          "supportPowConfig": 1,
          "trigTime": "1708198732743"
        },
```

![Снимок экрана от 2024-02-17 23-38-32](https://github.com/AlexxIT/SonoffLAN/assets/121604147/e4417480-d7be-4e74-80e1-ae46043ac5a3)
