### ISSUE TITLE
Fix does not set supported color modes warning

### ISSUE THREAD

**Issue by kelvinng1** [AlexxIT/SonoffLAN#1362]
Cannot change the device type of an TX switch to light using yaml in configuration.yaml as below:
```
sonoff:
  devices:
    10011xxxxx:
      device_class: light
      name: backyard_light
```
An error is captured in the HASS core log:
```
2024-03-17 00:30:15.811 WARNING (MainThread) [homeassistant.components.light] sonoff.sonoff_10011xxxxx (<class 'custom_components.sonoff.switch.XSwitch'>) does not set supported color modes, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/AlexxIT/SonoffLAN/issues
```
