### ISSUE TITLE
Add support Sonoff SWV

### ISSUE THREAD

**Issue by brononius** [AlexxIT/SonoffLAN#1497]
I’m new to Zigbee and using a Sonoff ZB Bridge-P with a Sonoff SWV (Smart Water Valve). I’ve set up the SonoffLAN integration via HACS, connected through the ‘AUTO’ method.

The valve appears as a device in Home Assistant after adding it through the eWeLink app and refreshing HA.

The problem:

1. When I turn the valve ON, the status in HA immediately switches to OFF, but the valve physically turns ON.
2. Turning the valve ON again, the status in HA stays ON.
3. Turning the valve OFF works correctly - both the status and the physical valve turn OFF.
4. Through the eWeLink app, it seems to be working fine.

Any suggestions on how to resolve this status mismatch?

Thanks in advance for any assistance!

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN?tab=readme-ov-file#issues

**Comment by brononius** [comment]
For the moment i've added a small rule to put it a second time ON. This works.

```
alias: SonOffKraanStatusCheck
description: ""
trigger:
  - platform: device
    type: turned_on
    device_id: 68f418251d408947863c809f26d032ed
    entity_id: 1ef333dd8c261fbe01156022326615bf
    domain: switch
condition: []
action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - type: turn_on
    device_id: 68f418251d408947863c809f26d032ed
    entity_id: 1ef333dd8c261fbe01156022326615bf
    domain: switch
mode: single

```

I didn't found any issues in the logs that relate to this.

The diagnostics:
[sonoff-01J73N995EM1AQ88AF83B0VQ5J-KraanSonoff1-68f418251d408947863c809f26d032ed.json](https://github.com/user-attachments/files/17095231/sonoff-01J73N995EM1AQ88AF83B0VQ5J-KraanSonoff1-68f418251d408947863c809f26d032ed.json)
