### ISSUE TITLE
Enhance TX Ultimate Switches with LED, Speaker, and Vibration Motor Support

### ISSUE THREAD

**Issue by Suleiman700** [AlexxIT/SonoffLAN#1524]
The TX Ultimate switches come with built-in LEDs, a speaker, and a vibration motor that would be great to control directly from Home Assistant. Adding support for the following features would enhance their usability:

- LED Control: Allow setting LED color, brightness, and patterns for visual alerts.

- Speaker Use: Enable playback of doorbell sounds or audio files on the switch speaker.

- Vibration Motor: Allow control over the vibration motor for tactile alerts.

If these require extensive setup, could you also provide guidance on sending API requests to control features like LED color and switch functionality?

Thank you!

**Comment by AlexxIT** [comment]
I can't do this because I don't have this device.

**Comment by Suleiman700** [comment]
@AlexxIT 
Can you try to describe how we TX Ultimate owners do that ?

**Comment by AlexxIT** [comment]
1. Enable debug logs
2. Call this commands from ewelink app
3. Implement this functions in HA

**Comment by Suleiman700** [comment]
@AlexxIT 
can you make it more detailed please :)

I've enabled the Sonoff debug logs and can see the logs,

What do you mean by 'call this command' ?

**Comment by AlexxIT** [comment]
Run these functions. To see what commands are used to call them.

**Comment by Fterol** [comment]
Hello all,
Im trying to implement the function for motor mode for 2 days now, but it seems im doing something wrong.
I see the logs in the debug logs. I see what action is "called". Im trying to call the action from Developer tools -> Actions -> sonoff.send_command but its not working.
If you can help me somehow it will be great. 
I can provide the logs from when i call the actions from app if you need it.

**Comment by pisanvs** [comment]
> Hello all, Im trying to implement the function for motor mode for 2 days now

Hey @Fterol, thanks for the help, but this is already implemented in PR #1587. We just need to wait until it's merged into master.

**Comment by mutlutekir** [comment]
> Run these functions. To see what commands are used to call them.

Hi @AlexxIT,
First of all, thank you for your amazing work on this integration!

I have been reverse-engineering the network logs for the Sonoff TX Ultimate (T5) smart switch. I discovered that we can achieve FULL control over its RGB LEDs, individual top/bottom LED strips, brightness, and built-in speaker without flashing ESPHome.


```
service: sonoff.send_command
data:
  device: "100228xxxx" # Enter your own device ID/mac address
  preEffects:
    lightEffect: 5     # Light animation style (between 0-5)
    soundEffect: 4     # Warning sound selection (between 0-5)
    statusLight: "on"  # on-off / solid light after warning
    statusLightTop: 1  # Top illumination on (1) / off (0)
    statusLightBelow: 1# Bottom illumination on (1) / off (0)
    r: 0               # Red tone of your desired color (0-255)
    g: 255             # Green tone of your desired color (0-255)
    b: 0               # Blue tone of your desired color (0-255)
    br: 100            # Your desired brightness level (0-100)
    volume: 80         # Your desired volume level (0-100)
```

Currently, users have to use sonoff.send_command to achieve this. It would be fantastic if we could expose these as native entities (number, select, switch) or as a dedicated service for TX Ultimate in SonoffLAN.

Here is the exact JSON payload format and the limits I have tested locally and on the cloud:

The Payload Structure:
```
JSON
{
  "preEffects": {
    "lightEffect": 5,      
    "soundEffect": 5,      
    "statusLight": "on",   
    "statusLightTop": 1,   
    "statusLightBelow": 1, 
    "r": 255,                
    "g": 255,              
    "b": 255,                
    "br": 100,             
    "volume": 100           
  }
}
```
Parameter Bounds for Entities:
lightEffect : int (0 to 5) -> (Could be select or number)

soundEffect : int (0 to 5) -> (Could be select or number)

statusLight : string ("on" or "off") -> (Could be switch)

statusLightTop : int (0 or 1) -> (Could be switch)

statusLightBelow : int (0 or 1) -> (Could be switch)

r, g, b : int (0 to 255) -> (Ideally handled via a mock Light entity or 3 number entities)

br (Brightness) : int (0 to 100) -> (Could be number or slider under light entity)

volume : int (0 to 100) -> (Could be number or slider under soundeffect)

(Also, the exact same structure applies to onEffects and offEffects to permanently change the default key-press feedback).

Suggested Python Implementation Logic (core/devices.py approach):
Since sending these values one-by-one might cause API spam (if a user slides the volume, we don't want it triggering the sound 10 times), it might be best handled by a custom handler that builds the preEffects dictionary from the current states before pushing:

```
Python
# Pseudo-code for handler logic
def set_tx_ultimate_effect(device, params: dict):
    # Base structure
    payload = {
        "preEffects": {
            "lightEffect": params.get("lightEffect", 0),
            "soundEffect": params.get("soundEffect", 0),
            "statusLight": params.get("statusLight", "on"),
            "statusLightTop": params.get("statusLightTop", 1),
            "statusLightBelow": params.get("statusLightBelow", 1),
            "r": params.get("r", 255),
            "g": params.get("g", 255),
            "b": params.get("b", 255),
            "br": params.get("br", 100),
            "volume": params.get("volume", 50)
        }
    }
    # Send to device
    device.send(payload)

```

Adding these as Configuration Entities or a specific service like sonoff.tx_ultimate_play_effect would be a game changer for the Home Assistant community.

I shared the video on my Youtube channel showing each variable and its effect on TX Ultimate. I don't know if it is possible to post here. 

I am ready to help with testing any beta releases for this feature. Thank you again!

**Comment by mutlutekir** [comment]
Anyone wondering this method, you can check the details from the link below.

https://community.home-assistant.io/t/full-native-control-of-sonoff-tx-ultimate-rgb-sound-effects-without-esphome/1008015

**Comment by mutlutekir** [comment]
I created script for this. You need Sonoff Lan HACS integration to use this. From the drop down menu, you can select your TX Ultimate device and configure light effect, color, brightness, sound effect etc, and use this script in automation.



```
alias: Sonoff TX Ultimate - Control Panel
description: >-
  Send color, brightness, and effect commands to your TX Ultimate device using a visual interface.
icon: mdi:lightbulb-multiple
fields:
  target_device:
    name: Sonoff Device
    description: Select the device you want to send commands to from the list.
    required: true
    selector:
      device:
        integration: sonoff
  rgb_color:
    name: Light Color
    description: Select a color from the palette for the halo light.
    default:
      - 255
      - 0
      - 0
    selector:
      color_rgb: {}
  brightness:
    name: Brightness
    description: Adjust the light intensity.
    default: 100
    selector:
      number:
        min: 0
        max: 100
        unit_of_measurement: "%"
  light_effect:
    name: Light Effect
    description: The visual animation the device will play.
    default: "0"
    selector:
      select:
        options:
          - label: 0 - Effect Off
            value: "0"
          - label: 1 - Wave Effect
            value: "1"
          - label: 2 - Breath Effect
            value: "2"
          - label: 3 - Cycle Effect
            value: "3"
          - label: 4 - Fast Transition
            value: "4"
          - label: 5 - Color Burst
            value: "5"
  sound_effect:
    name: Sound Effect
    description: The accompanying sound effect to play.
    default: "0"
    selector:
      select:
        options:
          - label: 0 - Sound Off
            value: "0"
          - label: 1 - Beep
            value: "1"
          - label: 2 - Double Beep
            value: "2"
          - label: 3 - Melody 1
            value: "3"
          - label: 4 - Alarm Chime
            value: "4"
          - label: 5 - Notification Sound
            value: "5"
  volume:
    name: Volume Level
    description: The volume level of the effect to be played.
    default: 80
    selector:
      number:
        min: 0
        max: 100
        unit_of_measurement: "%"
  top_light:
    name: Top Light Panel
    description: Should the top status lights be activated?
    default: true
    selector:
      boolean: {}
  bottom_light:
    name: Bottom Light Panel
    description: Should the bottom status lights be activated?
    default: true
    selector:
      boolean: {}
sequence:
  - variables:
      ewelink_id: >-
        {% set idents = device_attr(target_device, 'identifiers') | list %} {%
        set ns = namespace(id=target_device) %} {% for ident in idents %}
          {% if ident[0] == 'sonoff' %}
            {% set ns.id = ident[1] %}
          {% endif %}
        {% endfor %} {{ ns.id }}
  - data:
      device: "{{ ewelink_id }}"
      preEffects:
        lightEffect: "{{ light_effect | int }}"
        soundEffect: "{{ sound_effect | int }}"
        statusLight: "on"
        statusLightTop: "{{ 1 if top_light else 0 }}"
        statusLightBelow: "{{ 1 if bottom_light else 0 }}"
        r: "{{ rgb_color[0] }}"
        g: "{{ rgb_color[1] }}"
        b: "{{ rgb_color[2] }}"
        br: "{{ brightness | int }}"
        volume: "{{ volume | int }}"
    action: sonoff.send_command
```
