### ISSUE TITLE
Feature request: TX Ultimate Sound Action

### ISSUE THREAD

**Issue by stast1** [AlexxIT/SonoffLAN#1535]
Is it possible to add these commands to the device, for example as buttons?

Alarm:
```
action: sonoff.send_command
data:
  device: 100...
  soundAction: 1
```

Bell:
```
action: sonoff.send_command
data:
  device: 100...
  soundAction: 2
```
