### ISSUE TITLE
Add support Zigbee light with color_temp

### ISSUE THREAD

**Issue by AdimoUK** [AlexxIT/SonoffLAN#1557]
Hi

Got 3 [IKEA Tradfri GU10](https://www.ikea.com/gb/en/p/tradfri-led-bulb-gu10-345-lumen-smart-wireless-dimmable-white-spectrum-20547424/) bulbs linked to my Zigbee Bridge. All is working well in the eWeLink app, I have been able to pair those & control them using the app. However these are recognised by SonoffLAN as regular bulbs with no brightness / temperature control.

It initially picked these bulbs as switches, so I've gone ahead and configured them using config.yaml file to be lights. However this doesn't solve anything.

Here is the diagnostic (just relevant part, but let me know if you need the whole thing):
```yaml
"device": {
      "uiid": 1258,
      "params": {
        "bindInfos": "***",
        "subDevId": "9b2244feff8176281258",
        "parentid": "100233927e",
        "staMac": "***",
        "THIRD_PARTY_EQUIPMENT_INFORMATION": {
          "brand": "IKEA",
          "productModel": "TRADFRI bulb GU10 WS 345lm"
        },
        "switch": "on",
        "colorTemp": 26,
        "brightness": 100
      },
      "model": "ZigbeeTunableWhiteLight",
      "online": true,
      "local": null,
      "localtype": null,
      "host": null,
      "deviceid": "a4800c0a55"
```
Any chance of some guidance to get this to work?

On a side note, I can also confirm that I have also used the [IKEA Tradfri 10W driver](https://www.ikea.com/gb/en/p/tradfri-driver-for-wireless-control-smart-grey-50356187/) and this is picked up no problem, including brightness control fully working. FYI, here is the diagnostic relevant part again:

```yaml
"device": {
      "uiid": 1257,
      "params": {
        "bindInfos": "***",
        "subDevId": "e08a5dfefff8e2441257",
        "parentid": "100233927e",
        "staMac": "***",
        "THIRD_PARTY_EQUIPMENT_INFORMATION": {
          "brand": "IKEA",
          "productModel": "TRADFRI Driver 10W"
        },
        "switch": "on",
        "brightness": 100,
        "mode": 0
      },
      "model": "ZigbeeWhiteLight",
      "online": true,
      "local": null,
      "localtype": null,
      "host": null,
      "deviceid": "a4800bb997"
    }
```

I also am using the new [ZBBridge-U](https://sonoff.tech/product/gateway-and-sensors/zbbridge-u/) model, and that is also working well.

Many thanks in advance!

**Comment by AlexxIT** [comment]
Please set minimum colorTemp (yellow) from ewelink app and show device diagnostics. And set maximum colorTemp (white) and show device diagnostics.

> The colour temperature can be switched between 2200 Kelvin (warm glow), 2700 Kelvin (warm white) and 4000 Kelvin (cool white).

**Comment by AdimoUK** [comment]
Thanks for the quick response!

As I have a total of 3 of these bulbs, I have set one to 2200K and one to 4000K, both at full brightness. Here are they both:

```YAML
"a4800c0a57": {
  "uiid": 1258,
  "params": {
    "bindInfos": "***",
    "subDevId": "e52244feff8176281258",
    "parentid": "100233927e",
    "staMac": "***",
    "THIRD_PARTY_EQUIPMENT_INFORMATION": {
      "brand": "IKEA",
      "productModel": "TRADFRI bulb GU10 WS 345lm"
    },
    "switch": "on",
    "colorTemp": 0,
    "brightness": 100
  },
  "model": "ZigbeeTunableWhiteLight",
  "online": true,
  "local": null,
  "localtype": null,
  "host": null
},
"a4800c0a55": {
  "uiid": 1258,
  "params": {
    "bindInfos": "***",
    "subDevId": "9b2244feff8176281258",
    "parentid": "100233927e",
    "staMac": "***",
    "THIRD_PARTY_EQUIPMENT_INFORMATION": {
      "brand": "IKEA",
      "productModel": "TRADFRI bulb GU10 WS 345lm"
    },
    "switch": "on",
    "colorTemp": 100,
    "brightness": 100
  },
  "model": "ZigbeeTunableWhiteLight",
  "online": true,
  "local": null,
  "localtype": null,
  "host": null
}
```

Playing around with it to see values change, it seems that both brightness and colorTemp are on a scale of 0 - 100. (FYI - I had to click reload on the integration page each time to get the Download Diagnostics json file to update to current values). I'm guessing this is the info you are after.

Please let me know if I can help out any further!

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.8.2

**Comment by AdimoUK** [comment]
I'm afraid there's a 500 error from eweLink API now when running this. Unable to control the lights or see the status update (though the controls appear in a correct manner now).

![Image](https://github.com/user-attachments/assets/160850c6-5f7d-4026-a3c9-51c20e4f1fbc)

This is the diagnostic:

```YAML
"errors": [
      {
        "name": "custom_components.sonoff.core.ewelink.cloud",
        "message": [
          "Cloud ERROR: {'error': 500, 'deviceid': 'a4800c0a56', 'apikey': 'ceba33f9-5ecf-4744-8d7e-d726d386a25f', 'sequence': '1737048237592', 'uid': 'ceba33f9-5ecf-4744-8d7e-d726d386a25f'}"
        ],
        "level": "WARNING",
        "source": [
          "custom_components/sonoff/core/ewelink/cloud.py",
          603
        ],
        "timestamp": 1737048237.6540415,
        "exception": "",
        "count": 1,
        "first_occurred": 1737048237.6540415
      }
    ],
    "device": {
      "uiid": 1258,
      "params": {
        "bindInfos": "***",
        "subDevId": "97a309feff8176281258",
        "parentid": "100233927e",
        "staMac": "***",
        "THIRD_PARTY_EQUIPMENT_INFORMATION": {
          "brand": "IKEA",
          "productModel": "TRADFRI bulb GU10 WS 345lm"
        },
        "switch": "on",
        "colorTemp": 48,
        "brightness": 50,
        "null": "on"
      },
      "model": "ZigbeeTunableWhiteLight",
      "online": true,
      "local": null,
      "localtype": null,
      "host": null,
      "deviceid": "a4800c0a56"
    }
```

Please let me know how I can help to debug / diagnose the issues.
