### ISSUE TITLE
No Device - Only Entity

### ISSUE THREAD

**Issue by darkpwny** [AlexxIT/SonoffLAN#156]
Hi,

Installed the integration via HACS, and it found my eWeLink hot water switch as an entity, however there is no device associated with it and therefore many actions I cannot do in the automation section.

It works great as a toggle button via the entity on the lovelace UI and I can detect state change on an automation as thats done on entity, ut without a device - the automations come unstuck.  I can't write a trigger to turn it off....

Any ideas how to get it to generate a device along with the entity?

Current config section looks like:

```
sonoff:
  username: myemail@live.co.uk
  password: mypassword
  devices:
    1000d6386f:
      device_class: light
      name: Hot Water Light

```
Also attached screen shot of entity - not sure much use, it doesnt have ANYTHING associated with it.

The device I have is :
[FreeLeben Water Heater Smart Switches](https://www.amazon.co.uk/gp/product/B07T7N9LFJ/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1)

Thanks,
Rick

![capture](https://user-images.githubusercontent.com/25180061/83969691-4c498180-a8c9-11ea-99e9-e9d9bf8e13a0.png)
