### ISSUE TITLE
sonoff S31

### ISSUE THREAD

**Issue by goldbe4804** [AlexxIT/SonoffLAN#163]
i have 2 sonoff s31 and both show using no power or current when on, when turned off then they will show  a power & current value is there a way to fix this ??  Rpi4  with HA  0.1112  thanks jeff

**Comment by chairstacker** [comment]
Same here on HA 0.111.3 - it fixes itself after turning the switch on & off a few times, but when I unplug the S31 and plug it back in it's the same behavior.

**Comment by goldbe4804** [comment]
thanks for the info
so I should try to add that info to my confi yaml like this ? :
sonoff:
  username: abcd
  password: efgi
  sensors: [power, current, voltage]
  force_update: [power, current, voltage]
  scan_interval: '00:02:00'

jeff

**Comment by chairstacker** [comment]
That's what I did, with two [spaces] in front of every lie from username to scan_interval:
```
sonoff:
  username: abcd
  password: efgi
  sensors: [power, current, voltage]
  force_update: [power, current, voltage]
  scan_interval: '00:02:00'
```
