### ISSUE TITLE
Bridge Sonoff 443  receive signal from RF

### ISSUE THREAD

**Issue by aleconte1978** [AlexxIT/SonoffLAN#17]
Alex, can I receive RF information through a Sonoff bridge? In the integration example just send. You can tell me if it can be received and how is the code. As always, thank you very much for your time.

**Comment by AlexxIT** [comment]
There is an example in readme, here it is:
```
automation:
- alias: Test RF
  trigger:
    platform: event
    event_type: sonoff.remote
    event_data:
      command: 0
  action:
    service: homeassistant.toggle
    entity_id: remote.sonoff_1000abcdefg
```
You can receive only previously trained code.
The event will not contain the code itself, but its number in order in eWeLink App.
