### ISSUE TITLE
Wrong deviceid 22139 (GK-200MP2-B Camera)

### ISSUE THREAD

**Issue by seoulop** [AlexxIT/SonoffLAN#172]
Thank you for this wonderful custom component.

Now I'm having a problem with PTZ of GK-200MP2-B Camera.
I have 2 GK-200MP2-B, and one of them works perfectly, but the other one doesn't work PTZ function.

The log says 
'Wrong deviceid 22139' 
Logger: custom_components.sonoff
Source: custom_components/sonoff/__init__.py:215

I checked camera id hundreds times and it was correct.
What else can I try now?

Ps. I'm using Sonoff LAN v2.2.0 with Hassio HA 0.111.2 on the RP4 

A camera with script below works.
```yaml
sonoff_camera_left:
  sequence:
  - data:
      cmd: left
      device: 052xxx
    service: sonoff.send_command
```

And the other one with script below doesn't work.
```yaml
sonoff_camera3_left:
  sequence:
    - data:
        cmd: left
        device: 053xxx
      service: sonoff.send_command
```

The only difference is device id and they are all correct.

**Comment by AlexxIT** [comment]
I think you have something like this in config:

```yaml
script:
  left:
    sequence:
      - service: sonoff.send_command
        data:
          device: 22139
          cmd: left
```

Device must be 6 digits
