### ISSUE TITLE
multi-channel sonoff 4ch wont work

### ISSUE THREAD

**Issue by antoweb** [AlexxIT/SonoffLAN#174]
Hello,
when i put this in my conf the light is not added and remain switch type:
```
sonoff:
  username: !secret username_sonoff
  password: !secret sonoff_password
  devices:
    <sonoff-device-id>:
      device_class: [light, light, light, light]
      name: Sonoff 4CH
```

But The following sonoff touch  working good:

```
sonoff:
  username: !secret username_sonoff
  password: !secret sonoff_password
  devices:
    <sonoff-device-id>:
      device_class: [light, light, light]
      name: Sonoff T1 3C
```
