### ISSUE TITLE
Sonoff RF with Kerui KR-D026 (states on and off) door sensors

### ISSUE THREAD

**Issue by camui-alexandru** [AlexxIT/SonoffLAN#180]
I have this config:

```yaml
sonoff:
  username: xxxxxx@xxxxxxx.com
  password: xxxxxxxxx
  default_class: light
  sensors: [temperature, humidity, pir, door]
  mode: local
  reload: always
  debug: True
  rfbridge:
    Entrance_door:
     turn_on: 
     name: Door Sensor with two states
     device_class: door
     timeout: 0
     payload_off: turn_off Entrance_door
```

the problem is: when i restard home assistant, the entity show that door is closed, when i open the door, it shows door open, but this is it. It just remain open. Even if i close the door, it dosen't show in the entity.
