### ISSUE TITLE
Sonoff 4ch Pro R2 one light seems to randomly switch on

### ISSUE THREAD

**Issue by iamandymcinnes** [AlexxIT/SonoffLAN#183]
Hi

This is more of a question which may lead to me doing some more troubleshooting I think, but essentially I have 8 sonoff 4ch pro r2 devices in my house. These are working absolutely great and I use them in local mode only.

This is a snippet of my config but as everything connected is a light, they are all the same.

```
sonoff:
  username: !secret sonoff_username
  password: !secret sonoff_password
  mode: local
  reload: always  # update device list every time HA starts
  devices:
    1000xxxxx:
      device_class: [light,light,light,light]
      name: Basement Lights 1
```

I have something really strange happening with one the lights, whereby it seemingly comes on at random. This particular light has no automations or references anywhere in my home assistant config. I've got my config in github: https://github.com/mcinnes01/HomeAssistant-Config and have searched all the way through for references to the "light.brewery_light". I've even gone as far as renaming the entity id in home assistant to ensure there is nothing hiding. I've removed the integration and readded it, but something is still making it turn on sometimes, and I'm not sure what else I can do to track down what is triggering it to come on.

Any help would be much appreciated.

Andy
