### ISSUE TITLE
PSF-X67 freeze

### ISSUE THREAD

**Issue by slydiman** [AlexxIT/SonoffLAN#184]
I have the following device
https://aliexpress.ru/item/4000599724077.html
manufacturer: coolkit
model: PSF-X67
sw version: PSF-B67-GL v3.4.0

It is the switch with the following attributes power, voltage, current.

I see data changes only when I use eWeLink application.
Otherwise all data in HA is frozen.
I'm using hass.io on Raspberry PI4.
The main router is newest Keenetic Speedster.
I have created the second eWeLink account and shared the device.
HA uses the first account and eWeLink application uses the second account - nothing changed.
I tried the cloud mode and force_update: [power], but it did not help too
```
sonoff:
  username: !secret sonoff_username
  password: !secret sonoff_password
  mode: cloud
  force_update: [power]
  scan_interval: '00:00:05'
```
