### ISSUE TITLE
Door / Window Sensor Setup

### ISSUE THREAD

**Issue by rronni** [AlexxIT/SonoffLAN#185]
I've bought 10 of the "2 State" door / window sensors you suggested, (link below), but struggling to get them setup in order to display the Window Status in Home Assistant. A few questions if i may:

 - In the eWeLink App, what do i need to set them up as? 2 button or Alarms?

 - What should my config.yaml file look like? I've copied and pasted the current one below, (n.b: Button 1 is the received code for window open, and Button 2 is for door closed. I'll change this later once I have it working!

```
sonoff:
  username: !secret sonoff_username
  password: !secret sonoff_password
  #mode: local
  reload: always  # update device list every time HA starts
  force_update: [temperature, power]
  scan_interval: '00:05:00'  # (optional) default 5 minutes
  sensors: [temperature, humidity, power, current, voltage]  
  rfbridge:
    Window sensor:
      name: Kitchen Rear Right # optional, you can change sensor name
      device_class: window
      timeout: 5
    turn_on:
      name: Button 1
      device_class: window
      timeout: 0
      payload_off: turn_off  Button 2 # button/sensor name in eWeLink application
```

 - Am i correct in saying that once I have this working for one, I need to copy and paste the config another 9 times, but with different button names?

Link for the "2 state" door / window switches I've bought per your recommendation:
https://www.banggood.com/10Pcs-GS-WDS07-Wireless-Door-Magnetic-Strip-433MHz-for-Security-Alarm-Home-System-p-1597356.html?cur_warehouse=CN

Many Thanks!

**Comment by rronni** [comment]
Lost formatting on config.yaml above - This is what i currently have. 

Thanks!

sonoff:
  username: !secret sonoff_username
  password: !secret sonoff_password
  #mode: local
  reload: always  # update device list every time HA starts
  force_update: [temperature, power]
  scan_interval: '00:05:00'  # (optional) default 5 minutes
  sensors: [temperature, humidity, power, current, voltage]
  rfbridge:
    turn_on:
      name: Kitchen Rear Right Window
      device_class: window
      timeout: 0
      payload_off: turn_off  Button2 # button/sensor name in eWeLink application

**Comment by AlexxIT** [comment]
You need set them up as 2 button.
Sonoff Bridge support only 16 buttons - you can config only 8 your sensors...

`turn_on` in example - this is name "open button" of sensor 1 in ewelink app
`turn_off` - this is name "close button" of sensor 1 in ewelink app

`payload_off: "turn_off  Button2"` <= there may be a mistake

**Comment by rronni** [comment]
OK, so the whole RF Bridge config for a single Window Sensor using a 2 button control would be like this:

`rfbridge:
    turn_on: Button1 #<-Name of the "On" button in eWeLink app
      name: Kitchen Rear Right Window #<- Name of the 2 button sensor in 
      device_class: window
      timeout: 0
      turn_off:  Button2 # <- Name of the "Off" button in eWeLink app`

Or Am I way off here?

**Comment by rronni** [comment]
This is from the repository page, but there are 3 options included, (PIR, One state and 2 state sensor). Can you show me what your code looks like for a single 2 state sensor please? Or delete the code I don't need? Have tried everything i can think of, and found numerous ways to fail :)  Thanks for your support!

```
sonoff:
  rfbridge:
    PIR sensor:  # button/sensor name in eWeLink application
      device_class: motion  # e.g. door, motion, window
      timeout: 60  # optional (default 120), timeout in seconds for auto turn off
    Door sensor:
      name: Door Sensor with one state  # optional, you can change sensor name
      device_class: door
      timeout: 5
    turn_on:
      name: Door Sensor with two states
      device_class: door
      timeout: 0
      payload_off: turn_off  # button/sensor name in eWeLink application
    Button1:
      timeout: 1
```

**Comment by rronni** [comment]
Having tested with the rest of my config removed, and ONLY the above, It still doesn't work. I think there's something missing here...

Does anyone have this working yet, and willing to share the snippet of their config.yaml file for a 2 state door/ window sensor please?

**Comment by Fifar4** [comment]
how i add 2 sensor door ?

this is my code
  rfbridge:
    Door sensor:
       name: Door1  # optional, you can change sensor name
       device_class: door
       timeout: 5
   
    Door sensor:
       name: Door_main_close  # optional, you can change sensor name
       device_class: door
       timeout: 5  #5   

This code gives me an error:
duplicated mapping key at line 119, column -537:
        Door sensor:

**Comment by AlexxIT** [comment]
@rronni 

This is right version:

```rfbridge:
    Button1:  # <-Name of the "On" button in eWeLink app
      name: Kitchen Rear Right Window  # <- Name of the 
      device_class: window
      timeout: 0
      turn_off:  Button2 # <- Name of the "Off" button in eWeLink app```

**Comment by AlexxIT** [comment]
@Fifar4 

```
  rfbridge:
    Door sensor:  # <-- here you need different names in ewelink app
       name: Door1
       device_class: door
       timeout: 5
   
    Door sensor:  # <-- here you need different names in ewelink app
       name: Door_main_close
       device_class: door
       timeout: 5  #5   
```

**Comment by rronni** [comment]
@AlexxIT Looks like we're getting closer!.... The code below defines the entity "Kitchen Rear Right Window", and updates successfully when the first sensor is opened, (Button1 in the eweLink App is triggered), however doesn't seem to correctly define "Button2", so even when triggering "Button2 in ewelink, (i.e. closing the window), the status never udpates to "Closed". 

From what i can tell, the difference in the code snippet, (as pictured below), is that Button1 is in Blue (successfully defined as a sensor), but "Button2" isn't. I can see both firing when the window sensor is opened / closed in the logs / debug of HA. 

![image](https://user-images.githubusercontent.com/66040518/87471015-9125ae00-c615-11ea-938e-7c5f1cbc4fb0.png)

2 Button device in eweLink app:
![image](https://user-images.githubusercontent.com/66040518/87471239-eeb9fa80-c615-11ea-8e07-c872811cbc13.png)

Entity Created:
![image](https://user-images.githubusercontent.com/66040518/87471285-05605180-c616-11ea-896c-da3337fd6ebe.png)

Button1 fires successfully:
![image](https://user-images.githubusercontent.com/66040518/87471482-56704580-c616-11ea-890f-4ddabf540289.png)

Button2 fires successfully:
![image](https://user-images.githubusercontent.com/66040518/87471428-3f315800-c616-11ea-8c9b-2a0476066d11.png)

Thanks again for your support. Hoping it's something simple!

It would also be useful to confirm if i can just keep adding sensors, (Up to the maximum for a single RF Hub), by copying the same code, but defining different entities and button numbers for each?

**Comment by AlexxIT** [comment]
@rronni you and I did not read my docs :)

```
sonoff:
  rfbridge:
    turn_on:
      name: Button1
      device_class: window
      timeout: 0
      payload_off: Button2
```
