### ISSUE TITLE
RF Bridge - Binary Sensors loose state when Home Assistant restarts

### ISSUE THREAD

**Issue by andrepia** [AlexxIT/SonoffLAN#192]
Hi @AlexxIT !! First of all, I would like to thank you for the great work with Sonoff LAN! It really makes my life way easier!!
I have 3 RF door sensors on my Sonoff RF Bridge exposed to Home Assistant as below (and, btw, they are working great!):

```
sonoff:
    (...) user config ... etc... (...)
    rfbridge:
      casa_porta_abre: # Sensor da porta da casa
        name: casa_porta
        device_class: door
        timeout: 0
        payload_off: casa_porta_fecha
      suite_porta_abre: # Sensor da porta da suite
        name: suite_porta
        device_class: door
        timeout: 0
        payload_off: suite_porta_fecha
      quarto_porta_abre: # Sensor da porta do quarto
        name: quarto_porta
        device_class: door
        timeout: 0
        payload_off: quarto_porta_fecha
```

But every time I restart home assistant all the binary sensors goes to "off/closed" and I "loose" their state.
The question is: Is there a way to retain the open state on home assistant restart? I'm I missing something on the configuration?
Thanks in advance!!
