### ISSUE TITLE
Voltage Not Updating Sonoff v2.2.1

### ISSUE THREAD

**Issue by MitchHA** [AlexxIT/SonoffLAN#197]
Hi AlexxIT

I have been using your addon for a while and the Voltage sometimes takes 3 days to update.
It used to be very regular. Do you know why this is happening?
It would be great if you could look into this issue.

My voltage used to be too high 250+ and it caused equipment in my home to cut out. So monitoring the voltage has been very helpful for me.

p.s. this is the first time I have reported an issue on github

https://youtu.be/GGexOcgIBpE

Sonoff v2.2.1 via HACS
Home Assistant 0.112.4

```
sonoff:
  username: xxxxxxx
  password: xxxxxxx
  force_update: power #  scan_interval: '00:01:00'  # (optional) default 5 minutes
  sensors: power, current, voltage
  mode: cloud # , cloud
  scan_interval: '00:01:00' 
  devices:
    100064636e:
      name: Sonoff Pow
      force_update: True
```

Thanks
Mitch
