### ISSUE TITLE
.sonoff.json file does not restored when manual remove it.

### ISSUE THREAD

**Issue by PcOnline2004** [AlexxIT/SonoffLAN#202]
The .json file in /config does not restored when I manual remove it. I did try uninstall/reinstall SonoffLAN but get no luck. I have to try "always reload".
How could I fix this?

```
sonoff:
  username: !secret  sonoff_user
  password: !secret  sonoff_password
  force_update: [temperature, power]
  scan_interval: '00:00:05'  # (optional) default 5 minutes
  sensors: [temperature, humidity, power, current, voltage]
  mode: local
  reload: always 
```
