### ISSUE TITLE
Humidity sensor glitching since 2.3.0

### ISSUE THREAD

**Issue by hewwoworld** [AlexxIT/SonoffLAN#203]
![Humidity Glitch](https://user-images.githubusercontent.com/42094954/88210021-6f4aad80-cc4b-11ea-85fc-e35904a729de.png)
Since the SonoffLan update v2.3.0, the humidity sensor has been glitching out. It switches between percentage and decimal percentage e.g. 72% -> 0.72%. Any ideas?

**Comment by hewwoworld** [comment]
The issue disappears if i go back to 2.2.3.

**Comment by PcOnline2004** [comment]
> ![Humidity Glitch](https://user-images.githubusercontent.com/42094954/88210021-6f4aad80-cc4b-11ea-85fc-e35904a729de.png)
> Since the SonoffLan update v2.3.0, the humidity sensor has been glitching out. It switches between percentage and decimal percentage e.g. 72% -> 0.72%. Any ideas?

All sensors have gone when I update to v2.3.0. The TH now do not show temperature and humidity!!!

**Comment by AlexxIT** [comment]
Duplicate #201 

I added some code to fix ZigBee Humidity.
It probably broke TH.

**Comment by isorin** [comment]
Same here, I've noticed the same for all 3 of my TH16 sensors since I've updated to the latest version.
(not as severe as the one posted above thou')

![image](https://user-images.githubusercontent.com/17415569/88398838-d8eac900-cdbd-11ea-981d-032dcd40ead6.png)

![image](https://user-images.githubusercontent.com/17415569/88398906-f15ae380-cdbd-11ea-8b22-9ccd3ea9fab4.png)

**Comment by Fifar4** [comment]
Hey, the sensors zigbee SNZB-01(-04), work with conbee?

**Comment by vando** [comment]
In the meanwhile, I added a conditional in humidity sensors

```
# eWeLink Sonoff TH16
- platform: template
  sensors:
    deposito_humedad:
      friendly_name: Humedad deposito
      device_class: humidity
      unit_of_measurement: '%'
      value_template: >
        {% set val = state_attr('switch.sonoff_100085069c', 'humidity') %}
        {% if val > 0 %}{{ val }}{% else %}{{ val * 100 }}{% endif %}
```
