### ISSUE TITLE
RFBridge assistance

### ISSUE THREAD

**Issue by Ubergeeksov** [AlexxIT/SonoffLAN#208]
Hi,

Firstly, thank you for the work that you have done on SonoffLAN.

Secondly, I hope you are able (aka willing) to help me. I am a noob when it comes to bespoke home automation and Home Assistant in particular. I've read the help documentation but have struggled to follow much of it, as it seems to assume a certain degree of prior knowledge which, unfortunately, I am lacking. I have, however, managed to set it up with a few integrations by following various tutorials. I have also managed to successfully integrate SonoffLAN for my RF Bridge 433 and PIR and have set up a simple automation whereby my lights are turned on if motion is detected:

```
- id: '1595050806949'
  alias: Turn lights on when motion detected
  description: ''
  trigger:
  - event_data:
      name: PIR
    event_type: sonoff.remote
    platform: event
  condition: []
  action:
  - data:
      entity_id: switch.sonoff_office_1
    service: switch.turn_on
```

However, what I am also trying to achieve is for the lights to turn off if motion is not detected for a certain number of minutes. I have found this example: https://www.home-assistant.io/cookbook/turn_on_light_for_10_minutes_when_motion_detected/ which basically explains what I am trying to achieve, but I am struggling to understand how to use the state platform with SonoffLAN rather than event platform.

Any help would be very gratefully appreciated.

Thanks,

Richard

P.S. If anyone knows of a "Dummies Guide to Home Assistant" for complete newbies, I would also be very grateful.

**Comment by cybergrimes** [comment]
I would recommend posting this in the HA community forums, you'll get a lot more eyes on it.
For your question, I don't use any PIR sensors but I assume they'll have a state similar to on/off for motion detected.

Here's an example where I turn a light off after the state has been set to 'on' for 5 minutes

```
 #Turn off hallway light after 5 minutes
 - alias: Turn off hallway light
   initial_state: 'on'
   trigger:
     - platform: state
       entity_id: switch.ge_12722_onoff_relay_switch
       from: 'off'
       to: 'on'
       for:
         minutes: 5
   action:
    - service: switch.turn_off
      entity_id: switch.ge_12722_onoff_relay_switch
```
