### ISSUE TITLE
Camera entity

### ISSUE THREAD

**Issue by Jarpetnee** [AlexxIT/SonoffLAN#214]
Hi Alex et al,

Was just wondering how far off in the pipeline the camera entity is? Really looking forward to it.

Cheers

**Comment by ErikThiart** [comment]
Also, does anyone has any idea what protocol the PTZ uses? I would like to control the PTZ via luxriot.

**Comment by AlexxIT** [comment]
Oh, sorry. A lot of projects on my shoulders.

**Comment by Jarpetnee** [comment]
Hi @AlexxIT, no need to be sorry at all! Was just curious if you had a release date in mind. :)

**Comment by ErikThiart** [comment]
I'd like to help you, but I do not know where to begin. I have a couple of these cameras but I do not know what to do beyond that to help you (I'm just a PHP dev :P)

**Comment by AlexxIT** [comment]
For now you can create camera entity manually with camera generic+stream or camera ffmpeg components.

I have another project (hassio addon):
https://github.com/AlexxIT/hassio-addons/tree/master/rtsp2webrtc

It can show stream from this camera in real realtime. Without any delay of picture.

**Comment by diazwatson** [comment]
Can the live stream not be done already with ` camera_view: live`?

IE.:
```
title: Home
views:
  - path: default_view
    title: Home
    cards:
      - aspect_ratio: 0%
        camera_image: camera.kitchen
        camera_view: live
        entities: []
        title: Kitchen Camera
```
At least mine seems to update every second with this configuration
