### ISSUE TITLE
Sonoff POW history usage errors in log

### ISSUE THREAD

**Issue by guciopl** [AlexxIT/SonoffLAN#220]
I noticed I have few thousands lines of errors in .log file. All of them look like this:
https://pastebin.com/QZ6wqqhc

Here is fragment from configuration:
```
sensor:
- platform: template
  sensors:
    power_ups:
      friendly_name: UPS
      unit_of_measurement: W
      device_class: power
      value_template: "{{ state_attr('switch.sonoff_1000bda5e7', 'power') }}"    
    history1_ups:
      friendly_name: UPS today
      unit_of_measurement: kWh
      device_class: power
      value_template: "{{ state_attr('switch.sonoff_1000bda5e7', 'consumption')[0] | round(2) }}"
    history30_ups:
      friendly_name: UPS last 30 days
      unit_of_measurement: kWh
      device_class: power
      value_template: "{{ state_attr('switch.sonoff_1000bda5e7', 'consumption')[:30]|sum | round(2) }}" 
```

What may be wrong there? It was working without issues some versions earlier.
