### ISSUE TITLE
device_class/name not updating for all devices. 

### ISSUE THREAD

**Issue by warrendt** [AlexxIT/SonoffLAN#241]
Having an issue where some devices to not update their class and custom name. 
I have tried deleting the Sonoff.json and restarting multiple times. 
No apparent syntax errors. 
Is there a limit on how many devices you can customise? 
I have 18 switches I wish to make lights instead of switches. 
19 devices in total 

Using latest version of SonoffLAN 

arch | x86_64
-- | --
chassis | vm
dev | false
docker | true
docker_version | 19.03.11
hassio | true
host_os | HassOS 4.13
installation_type | Home Assistant OS
os_name | Linux
os_version | 5.4.63
python_version | 3.8.5
supervisor | 245
timezone | Africa/Johannesburg
version | 0.115.2
virtualenv | false

**Comment by warrendt** [comment]
Ping pong

**Comment by AlexxIT** [comment]
Show your config, how do you do it.

**Comment by warrendt** [comment]
sonoff:
  username: 
  password: 
  force_update: [temperature, power]
  scan_interval: '00:05:00'  # (optional) default 5 minutes
  sensors: [temperature, humidity, power, current, voltage]
  mode: cloud
  reload: always  # update device list every time HA starts
  debug: True  # you will get HA notification with a link to the logs page
  devices:
    100087002b_3:
      device_class: light
      #name: Back Garden Light
    100088f407:
      device_class: light
      #name: Dining Room Light
    10008703ba_1:
      device_class: light
      #name: Front Garden Light
    10008770ae:
      device_class: light
      #name: Jordan's Bedroom Light
    1000958194:
      device_class: light
      #name: Jordy's Bedroom Light
    10008708eb_1:
      device_class: light
      #name: Kids Bathroom
    100087002b_2:
      device_class: light
      #name: Kitchen Main
    100087002b_1:
      device_class: light
      #name: Kitchen Scullary
    100088f4c5:
      device_class: light
      #name: Lea's Office Light
    10008703ba_2:
      device_class: light
      #name: Lounge Light
    10008703ba_3:
      device_class: exclude
      #name: Lounge Spare Light
    100086fb49_1:
      device_class: light
      #name: Main Bedroom Bathroom
    100086fb49_2:
      device_class: light
      #name: Main Bedroom Cupboard
    100086fb49_3:
      device_class: light
      #name: Main Bedroom Light
    10008708eb_2:
      device_class: light
      #name: Passage Light
    10008708eb_3:
      device_class: exclude
      #name: Passage Spare
    1000957b99:
      device_class: light
      #name: Spare Room Light
    10009572ef_1:
      device_class: light
      #name: Warren's Office Corner Light
    10009572ef_2:
      device_class: light
      #name: Warren's Office Light

**Comment by warrendt** [comment]
Ignore the hashes in the name field, that was for troubleshooting.

**Comment by AlexxIT** [comment]
You are setting `device_class` incorrectly for multi-channel devices. Check readme

**Comment by warrendt** [comment]
Ah, I see, I missed that, thank you :)

**Comment by gregf888** [comment]
I have a similar problem.  Using a 4ch Pro (1000737ff5) I cannot update any of the device classes for individual channels
The first two entries for single channel devices work, but the entries for the 4ch Pro device have no effect 
```
  devices:
    10006c1b20:
      device_class: light
    10007fce2e: # Downstairs blinds up (temp)
      device_class: cover
    # 1000737ff5: #
       # device_class: switch
       # device_class: switch
       # device_class: switch
       # device_class: cover
#    1000737ff5_1: # Watering # OK as switch
#    1000737ff5_2: # Spare1
#    1000737ff5_3: # Spare2
    1000737ff5_4: # Garage door
       device_class: [cover]

```

**Comment by AlexxIT** [comment]
@gregf888 You should also read the readme carefully :)

**Comment by AlexxIT** [comment]
@warrendt Describe the task in more detail

**Comment by gregf888** [comment]
You are right of course Alex ;)
I have been wrestling with this 4ch Pro for days now and have tried so many changes.  Here is how it is now.  The Real Problem is that a device_class of cover does not work.  It doesn't really matter, I have worked around it.

```
    1000737ff5: #
       device_class:
         - switch # Watering
         - light  # Spare1
         - light  # Spare2
         - switch # Garage Door (switch, light, fan works but not cover)

```

**Comment by gregf888** [comment]
And thanks for your non stop assistance Alexx

**Comment by gregf888** [comment]
> How can I exclude a single gang on a multi channel device ?

I do this by disabling it in configuration > entities

**Comment by warrendt** [comment]
> @warrendt Describe the task in more detail

Thanks for all the assistance, 
Basically I have 3 switches on the multi switch device. 
2 are in use, 1 is disabled (not connected to anything) 
I would like to disable the not in use switch on the multi device. 
So like an exclude, but the exclude excludes the entire device. I just want to disable one switch on the multi

**Comment by warrendt** [comment]
> > How can I exclude a single gang on a multi channel device ?
> 
> I do this by disabling it in configuration > entities

let me do this rather :)

**Comment by AlexxIT** [comment]
@gregf888 #78

**Comment by AlexxIT** [comment]
@warrendt 
```yaml
# if last channel disabled
device_class:
- light
- light
- light

# if middle channel disabled
device_class:
- light: 1
- light: 2
- light: 4
```
