### ISSUE TITLE
No sensors listed, just switches

### ISSUE THREAD

**Issue by hugosteyn** [AlexxIT/SonoffLAN#247]
When I install the component, the sonoff switches show up under Developer tools in HA, but the sensors are missing.  Here is what I have in configuration.yaml for the sonoff devices:

```yaml
sonoff:
  username: xxxxxxxx(not shown here)
  password: xxxxxxx(not shown here)
  sensors: [temperature]
  force_update: [temperature]
  scan_interval: '00:01:00'  # (optional) default 5 minutes
```

![2020-09-28 10_34_39-Developer Tools - Home Assistant](https://user-images.githubusercontent.com/72010476/94409300-475d5600-0176-11eb-9869-0e61b3c8b4c3.png)

I have the latest version of the SonoffLAN component, and I am running Home Assistant 0.115.3
