### ISSUE TITLE
Emulated Hue and SonoffLAN

### ISSUE THREAD

**Issue by km2000us** [AlexxIT/SonoffLAN#268]
Thanks for this integration. 

I have setup 3 sonoff devices, 2 Sonoff Mini and 1 Sonoff Basic, and they are working well within the HomeAssistant lovelace interface.  

I have exposed all 3 devices to Alexa using the Emulated Hue integration.  However, those devices are not discovered by Alexa.  All other devices work with Alexa without a problem.  I can also control those devices using my Harmony Remote (as it can pick up devices exposed by Emulated Hue).

I have tried forgetting forgetting all discovered devices under Alexa and also deleted the emulated_hue.json file, for a fresh start of the discovery process.  

Any possible solutions would be much appreciated.

**Comment by harmpert** [comment]
Why don't you use the sonoff integration (Sonoff LAN) offered in HACS? It works for me, all sonoft switches are available in Google assissant through the ewelink  app/

**Comment by km2000us** [comment]
@harmpert I am using the SonoffLAN integration from HACS.   I am trying to control them using Alexa.

**Comment by km2000us** [comment]
If anyone has this or similar issue, this thread will help:

[https://github.com/home-assistant/core/issues/30013](url)

The issue seems to be Alexa does not discover On/Off Iights or switches. 

A workaround is to create a light entity that has a brightness setting (any dummy setting will do) using the template platform.  The new light entity will then be discoverable using Alexa.

Here is an example:
```

input_number:
  dummy_light
    min: 0
    max: 255

light:
  - platform: template
    lights:
      kitchen_lights:
        value_template: "{{ is_state('switch.sonoff_xxxxxxxxxxx', 'on') }}"
        friendly_name: 'Kitchen Lights'
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.sonoff_xxxxxxxxxxx
        turn_off:
          service: switch.turn_off
          data:
            entity_id: switch.sonoff_xxxxxxxxxxx   
        set_level:
          service: input_number.set_value
          data_template:
            value: "{{ brightness }}"
            entity_id: input_number.dummy_light

```
