### ISSUE TITLE
Sonoff Zigbee 3.0 Bridge - sensors unavailable

### ISSUE THREAD

**Issue by alexdj71** [AlexxIT/SonoffLAN#279]
Hi, I am testing a couple of sensors with a Sonoff Zigbee hub and during the day, they become unavailable for some reason I don't know.
They all show perfectly in HA, they function ok as well but suddenly, they become unavailable.
Aprox. 1 hour later they come back online, without any interference. 
My setup includes:
1 sonoff Bridge Zigbee 3.0
1 Sonoff Motin sensor
1 Sonoff door/window Sensor
1 Smart Life door/window sensor.

My Yaml file is:

```yaml
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

#google credencials
#google:
#  client_id: 0-0.apps00.com
#  client_secret: 000

#Raspberry Pi GPIO's

binary_sensor:
  - platform: rpi_gpio
    ports:
      11: Water Sensor
    invert_logic: true  
     


#SonOff
sonoff:
  username: username
  password: pasword
  force_update: True
  scan_interval: '00:01:00'  # (optional) default 5 minutes
  mode: auto
  reload: always  # update device list every time HA starts
  sensors: [temperature, humidity, power, current, voltage]
```

____________________
LOG FILE
4z_switch1 turned off
9:41:52 PM - 2 hours ago
4z_switch2 turned off
9:41:52 PM - 2 hours ago
4z_switch3 turned off
9:41:51 PM - 2 hours ago
4z_switch4 turned off
9:41:51 PM - 2 hours ago
4z_switch1 turned on
9:41:40 PM - 2 hours ago
Presenca1 cleared (no motion detected)
9:33:04 PM - 3 hours ago
Porta SM Life was closed
9:23:49 PM - 3 hours ago
Hzig 1 turned off
9:23:48 PM - 3 hours ago
Porta became unavailable
9:23:26 PM - 3 hours ago
Presenca1 became unavailable
9:23:26 PM - 3 hours ago
Hzig 1 became unavailable
9:23:26 PM - 3 hours ago
Porta SM Life became unavailable
8:27:06 PM - 4 hours ago
Presenca1 cleared (no motion detected)
8:12:19 PM - 4 hours ago
Porta was closed
8:12:18 PM - 4 hours ago
Porta became unavailable
7:51:41 PM - 4 hours ago
Presenca1 became unavailable
6:35:16 PM - 6 hours ago
Sun set
6:31:30 PM - 6 hours ago
Porta was closed
6:11:59 PM - 6 hours ago
Porta became unavailable
5:51:21 PM - 6 hours ago

I'd appreciate some feedback, please.
