### ISSUE TITLE
Nothing happens :( 

### ISSUE THREAD

**Issue by Violo1975** [AlexxIT/SonoffLAN#287]
Hi Everybody, I'm a newby...
I have follow all the step using HACS and my Yaml file is:

```
# SonOff
sonoff:
  username: xxx@gmail.com
  password: xxx
  force_update: True
  scan_interval: '00:01:00'  # (optional) default 5 minutes
  mode: auto
  reload: always  # update device list every time HA starts
```
but nothing happen, someone can help me.....many tks

for info I've to add two sensors:
- 4CH Pro R2
- 2CH with RF 433 MHz

System info:
Versione HS: 0.118.1
Version OS: 4.19.127-v7

Grazie a tutti :)
