### ISSUE TITLE
cloud mode crushes logics

### ISSUE THREAD

**Issue by gribouk** [AlexxIT/SonoffLAN#292]
Hello!
Is it possible to make the devices work in local mode, which support local mode, and in cloud mode, the devices supporting cloud mode only?

The issue: as of this midnight, I belive, the Chinise cloud experiences some issues again, which can be discovered through the fact, that it does not update itself on device state update: for example, you press a button on a 4CH, it turns on a channel, but state in eWelink does not change, maybe once out of 10 times it reacts, but the other times fails. As the result, when my "advanced logics" scripts  in HA do certain computations and change the state of 4CH, the cloud does not follow. Instead, after some time, it decides to update my entities in HA (or vice versa, HA wants to synchronise itself), and changes their state to the ones, it refused to change already (the wrong ones to that moment)! And all my 'advanced logics' crushes... I spent whole day investigatig the cause of the sudden malfunction which was not there  yesterday evening before discovering this. With local mode in the setup I loose zigbee temperature sensors which data I need for "advanced logics"! Hence the question: is it possible to start zigbee in cloud and the rest of the field in local modes?

**Comment by AlexxIT** [comment]
What's your current config?

**Comment by gribouk** [comment]
This is eWelink's part only:

```
########################## EWeLink Section BEGIN ####################################        
sonoff:
  username: gribouk@gmail.com
  password: 192837465qazwsx
##  mode: local
##  reload: always  # update device list every time HA starts  
  
  sensors: [temperature, humidity, power, current, voltage]
  force_update: [temperature, humidity, power, current, voltage]
  scan_interval: '00:00:10'  # (optional) default 5 minutes
  
  
  
  
  rfbridge:
    dining1:  # sensor name in eWeLink application
      device_class: motion
      timeout: 120 
    kitchen1:  # sensor name in eWeLink application
      device_class: motion
      timeout: 120 
    stairs_to_spa:  # sensor name in eWeLink application
      device_class: motion
      timeout: 20
    stairs_up_second_floor:  # sensor name in eWeLink application
      device_class: motion
      timeout: 20 
    stairs_down_first_floor:  # sensor name in eWeLink application
      device_class: motion
      timeout: 20 
    library:  # sensor name in eWeLink application
      device_class: motion
      timeout: 120
    first_floor_wc:  # sensor name in eWeLink application
      device_class: motion
      timeout: 120 
    gym1:  # sensor name in eWeLink application
      device_class: motion
      timeout: 120 
    laundry:  # sensor name in eWeLink application
      device_class: motion
      timeout: 120 
    electricity:  # sensor name in eWeLink application
      device_class: motion
      timeout: 120
    boiler_room:  # sensor name in eWeLink application
      device_class: motion
      timeout: 120
    spa_massage:  # sensor name in eWeLink application
      device_class: motion
      timeout: 120
    spa_wc:  # sensor name in eWeLink application
      device_class: motion
      timeout: 120
    spa_shawer:  # sensor name in eWeLink application
      device_class: motion
      timeout: 120
    basement_corridor:  # sensor name in eWeLink application
      device_class: motion
      timeout: 20 
    basement_corridor1:  # sensor name in eWeLink application
      device_class: motion
      timeout: 20 
    wardrobe:  # sensor name in eWeLink application
      device_class: motion
      timeout: 120 
    corridor_second_floor1:  # sensor name in eWeLink application
      device_class: motion
      timeout: 20
    master_wc:  # sensor name in eWeLink application
      device_class: motion
      timeout: 120
    guest_wc1:  # sensor name in eWeLink application
      device_class: motion
      timeout: 120 
    guest_wc2:  # sensor name in eWeLink application
      device_class: motion
      timeout: 120
    master_wardrobe:  # sensor name in eWeLink application
      device_class: motion
      timeout: 120 
    master_corridor:  # sensor name in eWeLink application
      device_class: motion
      timeout: 20
    storage:  # sensor name in eWeLink application
      device_class: motion
      timeout: 120 

########################### EWeLink Section END ################################ 

```
