### ISSUE TITLE
Devices Not Showing In Home Assistant

### ISSUE THREAD

**Issue by nathanmay** [AlexxIT/SonoffLAN#294]
I have a Sonoff S26 setup within the eWeLink app and works fine. However I have installed this addon within HACS and added the configuration as per the documnetation however no devices are showing up in Home Assistant.
Configuration.yaml
```
### Sonoff Settings ###  
sonoff:
  username: my@email.com
  password: MyPassword
```

Device: Sonoff S26 (Firmware version 3.5.0)

Android App V4.7.0
