### ISSUE TITLE
Sonoff D1 in DIY mode FW 3.5.0 not recognized as a light device class

### ISSUE THREAD

**Issue by Joao-Sousa-71** [AlexxIT/SonoffLAN#318]
Hello, the Sonoff in DIY mode is not recognized as a light device and is added a switch. I've already force the device class by adding the following:
```yaml
Sonoff:
   devices:
      1000d7b012:
      device_class: light
      name: Sonoff D1
```

But the dimmable feature is not available.
I sense the integration is not receiving the information required to identify properly the Sonoff model and therefore is adding as a switch which is the default class. Available to provide any log, or information that can help to troubleshoot this. Thank you!
