### ISSUE TITLE
Light Symbol

### ISSUE THREAD

**Issue by aaewalsh** [AlexxIT/SonoffLAN#33]
Hi,

First of all, I would like to tell you how amazing this plugin is and how it has saved me hours.

I have one question. in the image below you can see the master bedroom lamps symbol is a lightning bolt. is there a way to change it to a light bulb?

If you could help i would really appreciate it.

Kind Regards

Adam

![image](https://user-images.githubusercontent.com/54256281/74744437-7a725b00-521f-11ea-8677-1bc1529f4dd7.png)

**Comment by AlexxIT** [comment]
```
sonoff:
  username:
  password:
  devices:
    10002777e3:
      device_class: light
```
entity_id will change!
