### ISSUE TITLE
USB Switch Device Class

### ISSUE THREAD

**Issue by GHaigh** [AlexxIT/SonoffLAN#332]
Hi there

I am unable to change the device class from light to switch for the Sonoff USB switch.  When I change in in configuration.yaml the device is no longer discovered by the plug in.

My configuration.yaml is as follows and the other devices I change class on work without issue:

Any help appreciated, thanks

```yaml
# ewelink and Sonoff
sonoff:
  username: myemail
  password: mypassword
  reload: always
  default_class: light
  devices:
    1000abcde: # Study USB Switch
     device_class: switch 
     name: USB Switch
    1000fghij: # Irrigation Controller Sonoff 4CH
      device_class: [switch, switch, switch, switch]
      name: Irrigation Controller
    1000klmno:
      device_class: switch
      name: Tool Cupboard
```
