### ISSUE TITLE
DIY Item not Working need some advice 

### ISSUE THREAD

**Issue by thorrrr** [AlexxIT/SonoffLAN#370]
HI
I have a 2 gang Wifi light switch which i have in eWeLink and need to know if your SonoffLAN would be able to parse it to HA.
FYI the switch see [here](https://photos.app.goo.gl/1GXLUxFsxZe3idwe9) is meant to be used in a Smart Life / Tuya app.
But i have never been able to get it to be discovered and have spent 2 hours trying in both apps.
But soon as i try with eWelink it finds it in 10 seconds!!!!
If works fully and is passed to Alexa no issue. But i am trying to get it into HA.
But HA is not even finding it the code i am using is your DIY example but I am new to HA some just hoping you can help me.
My code is 

```
sonoff:
  username: {email used in eWelink}
  password: {pass used in eWelink}
  devices:  
  1000XXXX247:
  device_class: light
  name: Sonoff Basic
```
