### ISSUE TITLE
Sonoff B1, set scenes config and execute error

### ISSUE THREAD

**Issue by TheBoojah** [AlexxIT/SonoffLAN#383]
When setting up a scene with a sonoff B1 lamp, it should set either the color value or the color temp. However while it works fine in the editor, one of the recorded values in the scenes.yaml file is set to null. This throws an error when starting the scene, and the lamp does not change scene.

Like this from my scene.yaml:
```
    light.sonoff_10002bbc45:
      min_mireds: 1
      max_mireds: 3
      manufacturer: Sonoff
      model: B1
      sw_version: PSF-BLB-GL v2.6.0
      cloud: online
      rssi: -45
      brightness: 255
      **hs_color:**
      color_temp: 3
      friendly_name: Floor
      supported_features: 19
      state: 'on'
```

If this scene is run the following error occurs:
`Error while executing automation automation.turn_off_lights: None for dictionary value @ data['hs_color']`

Workaround:
Just delete the line with the missing value, and it all works. However if you edit the scene the line will be re-added thus breaking it again.

Hopefully this behavior could be fixed. Thanks!
