### ISSUE TITLE
Switch keeps the same state

### ISSUE THREAD

**Issue by grandchamp** [AlexxIT/SonoffLAN#4]
Hi.
I'm trying to use with my email and password, without any work on private keys, etc.
I'm using a Sonoff Micro USB.

So far it's working, but the state of the switch keeps on even if the real switch is off.
Eg:
The switch is ON on HA, i press it to go OFF, the real switch goes OFF but after 1 second the switch on HA becomes ON again, but the real switch stays OFF.
If i want to make the real switch ON again i have to press twice on HA (1 to go OFF and 1 to go ON again) and the real switch goes ON.

What could be the issue?

**Comment by grandchamp** [comment]
What i got from the logs:

for OFF
```
home-assistant   | 2020-01-31 14:39:50 DEBUG (SyncWorker_7) [custom_components.sonoff] Send switches to XXXXX: {'sequence': '1580481590', 'deviceid': 'XXXXX', 'selfApikey': '123', 'data': 'XXXXXXXXXXXXXXXXXXX', 'encrypt': True, 'iv': XXXXXXXXXXXXXX'}
home-assistant   | 2020-01-31 14:39:50 DEBUG (SyncWorker_7) [custom_components.sonoff] {"sequence":"1580481590","seq":36,"error":0}
```

for ON
```
home-assistant   | 2020-01-31 14:40:55 DEBUG (SyncWorker_19) [custom_components.sonoff] Send switches to XXXXX: {'sequence': '1580481655', 'deviceid': 'XXXXX', 'selfApikey': '123', 'data': 'XXXXXXXX', 'encrypt': True, 'iv': 'XXXXXXXXXX'}
home-assistant   | 2020-01-31 14:40:55 DEBUG (SyncWorker_19) [custom_components.sonoff] {"sequence":"1580481655","seq":38,"error":0}
```

**Comment by AlexxIT** [comment]
@grandchamp Sonoff devices send their status with Multicast.
I think, HA don't receive new Micro USB status after send command to it.
Have you other Sonoff devices?
Does the status in HA change if you switch the device manually or in eWeLink app?

**Comment by grandchamp** [comment]
Sorry, I don't have any other sonoff devices to test unfortunately.
The status don't change also if I trigger through the eWeLink app.

**Comment by AlexxIT** [comment]
It may be problems in your local network with multicast.
What model of your router?
I don't have Micro USB, but other users have no problem with it.

**Comment by grandchamp** [comment]
I use a Huawei HG659 provided by Vodafone. Will try to check if there's any setting related with multicast.
I already have rebooted but didnt work.

**Comment by grandchamp** [comment]
Seems like all the multicast settings are fine on my router.
Could the problem be because i run homeassistant in a docker container?

**Comment by AlexxIT** [comment]
@grandchamp Yes! If you proxy only one port to container (`-p 8123:8123`) - multicast will not work. You need to proxy the entire network (`--network host`)

**Comment by grandchamp** [comment]
My current config already covers that:
```
    homeassistant:
        restart: always
        privileged: true
        container_name: home-assistant
        image: homeassistant/raspberrypi3-homeassistant:stable
        volumes:
         - ./hassio:/config
         - /etc/localtime:/etc/localtime:ro
         - ../dehydrated/certs/grandchamp.duckdns.org:/config/certs #must create via mkdir the certs dir
        environment:
         TZ: Europe/Dublin
        ports:
         - "8123:8123"
        depends_on:
         - psql
         - mosquitto
        healthcheck:
         test: "curl --connect-timeout 10 --silent -f https://myhomeassistant:8123/ || exit 1"
         interval: 45s
         timeout: 30s
         retries: 3
        network_mode: host
```
