### ISSUE TITLE
Problem with automation with SONOFF SNZB-04 sensor

### ISSUE THREAD

**Issue by vdbosch** [AlexxIT/SonoffLAN#435]
Hi,

I have installed your SonoffLAN succesful. I see the sensor in LOVELACE and information is updated.
When I create an automation it doesn't react on the trigger.
I am a beginner with HA and I think I do something wrong (see attached automation.yaml)

What do I wrong?

Thanks already for your support.

Rob

In the automations.yaml next info is in:
```
- id: '1615998130041'
  alias: test1
  description: test1
  trigger: []
  condition: []
  action: []
  mode: single
- id: '1616162863125'
  alias: test1
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.sonoff_a48000aa3d
    to: Closed
    attribute: device_class
  condition: []
  action:
  - type: toggle
    device_id: 4699860caa37cdb35bf4ddac811dde0c
    entity_id: switch.eb26b575a68d5e71ddseim
    domain: switch
  mode: single
```
