### ISSUE TITLE
Noobe setup sonoff zigbee bridge

### ISSUE THREAD

**Issue by mac-city** [AlexxIT/SonoffLAN#449]
<img width="549" alt="Screen Shot 2021-04-04 at 4 19 04 PM" src="https://user-images.githubusercontent.com/46912307/113520522-a3f46000-9561-11eb-8fc7-9b3f5d266e28.png">

I hope it is ok to ask support questions here that are not necessarily a bug.  I am not understanding how to add or pair switches and sensors now that I have the zigbee bridge working, I believe as expected in home assistant.  I can flip the switch and the green led comes on so seems to be in pairing mode, but when putting switches or sensors in `pairing` mode too, I am not sure what happens next.  I am not getting any new devices showing up in my devices.  I am using the following entry in configuration.yaml...

```
sonoff:
  username: !secret sonoff
  password: !secret sonoff_pass
  force_update: [temperature, power]
  scan_interval: '00:05:00'  # (optional) default 5 minutes
  sensors: [temperature, humidity, power, current, voltage]
```

It seems I am not supposed to add a ZHA integration in HA, only the HACS, correct?  Am I missing something simple?
