### ISSUE TITLE
Support non-original firmware

### ISSUE THREAD

**Issue by frakman1** [AlexxIT/SonoffLAN#454]
I already flashed all my Sonoff devices with the SmartThings-friendly firmware described [here](https://community.smartthings.com/t/release-sonoff-sonoff-th-s20-dual-4ch-pow-touch-device-handler-smartapp-5-10-smart-switches/45957).
My questions is this. Is there a way to add these devices to the sonoff configuration file (under `sonoff:`)  as a generic switch? The on/off URLs are simply:

| Data      | URL | Example Result |
| - | - | - |
| ON      | `http://[IP]/on`       | `{"type":"relay", "number":"1", "power":"on"}`|
| OFF   | `http://[IP]/off`        | `{"type":"relay", "number":"1", "power":"off"}`|
| STATUS   | `http://[IP]/status`        | `{"power":"on", "uptime":"2 days and 10:45:39", "temperature":"74.66", "scale":"F", "humidity":"99.90"}` |

If not, is there a way to add them as generic IP switches in HomeAssistant (i.e. outside of this integration) using those URLs?

**Comment by AlexxIT** [comment]
You can try use
https://www.home-assistant.io/integrations/switch.rest/
or
https://www.home-assistant.io/integrations/switch.command_line/
and curl...

**Comment by frakman1** [comment]
Thanks!

For others who are looking for a solution, I got it to work using this block in `configuration.yaml`

```yaml
switch:
  - platform: command_line
    switches:
      sonoff_tv:
        command_on: curl http://[IP]/on
        command_off: curl http://[IP]/off
        command_state: curl http://[IP]/status
        value_template: '{{ value_json.power == "on" }}'
        friendly_name: Living Room TV

```
