### ISSUE TITLE
Sonoff Pow Consumption Reseting at 22:00h

### ISSUE THREAD

**Issue by renanwillian** [AlexxIT/SonoffLAN#459]
The first element in consumption is reseting every day at 22:00h instead of 00:00h, I believe it could be related with the timezone GMT-3. How can I fix this?

```
sensor:
- platform: template
  sensors:
    today_consumption:
      friendly_name: Today consumpion
      unit_of_measurement: kWh
      value_template: "{{ state_attr('switch.sonoff_1000abcdef', 'consumption').0 }}"
```

![image](https://user-images.githubusercontent.com/30376796/113959355-1894fc00-97f9-11eb-88bd-078e2531affe.png)

**Comment by AlexxIT** [comment]
I don't know. This is how ewelink servers work

**Comment by renanwillian** [comment]
I found this workaround with utility_meter:

```
sensor:
- platform: template
  sensors:
    today_consumption:
      friendly_name: Today consumpion
      unit_of_measurement: kWh
      value_template: "{{ state_attr('switch.sonoff_1000abcdef', 'consumption').0 }}"

utility_meter:
  today_consumption_meter:
    source: sensor.today_consumption
    cycle: daily
```

The utility_meter is reseting correctly at 00:00h:
![image](https://user-images.githubusercontent.com/30376796/114419002-6c04a280-9b89-11eb-91fc-f8416b26184d.png)
