### ISSUE TITLE
RF433 Bridge lost ID's of device on last (2.4.4) update

### ISSUE THREAD

**Issue by mphysic** [AlexxIT/SonoffLAN#501]
Just updated from 2.4.3 to 2.4.4 and got some bug.
All the sensors connected to my bridge became: unnamed device, unnamed device2 etc
I have not changing any of config options
config.yaml 
```
sonoff:
  username: yyy
  password: xxx
  mode: cloud
  force_update: [temperature, humidity, power]
  scan_interval: '00:05:00'  # (optional) default 5 minutes
  sensors: [temperature, humidity, power, current, voltage]
  rfbridge:
    Smoke1:
      name: Smoke Gost
      device_class: smoke
      timeout: 15
    Smoke2t:
      name: Smoke Tech
      device_class: smoke
      timeout: 15
    Smoke3s:
      name: Smoke Spaln
      device_class: smoke
      timeout: 15
    Smoke4d:
      name: Smoke Det
      device_class: smoke
      timeout: 15
    Leak1:
      name: Leak TechRoom
      device_class: moisture
      timeout: 30    
    PIR1:
      name: PIR-1
      device_class: motion
      timeout: 30
```
![hass-sonoff-1](https://user-images.githubusercontent.com/72446602/118122817-0ad82500-b3fc-11eb-9ff0-21077a56377f.PNG)
