### ISSUE TITLE
Sonoff TX shown but unable to turn off or on

### ISSUE THREAD

**Issue by ranrinc** [AlexxIT/SonoffLAN#503]
I'm able to show my new TX wall switch. It appears to be able to get the state of both switches however, it fails to turn off or on from HA. Unsure how to fix this since it is now working from ewelink apps but not working from HA.

![Screen Shot 2021-05-15 at 2 13 01 PM](https://user-images.githubusercontent.com/15801696/118351726-bcf02800-b587-11eb-97af-9e38fd249406.png)

Anyone able to help?

**Comment by AlexxIT** [comment]
Show your config

**Comment by ranrinc** [comment]
my sonoff config

```
sonoff:
  username: !secret sonoff_user
  password: !secret sonoff_pass
  mode: local
  #reload: always
```

Lovelace
```
cards:
  - type: vertical-stack
    cards:
      - cards:
          - type: horizontal-stack
            title: Bathroom
            cards:
              - type: 'custom:button-card'
                color_type: blank-card
              - type: 'custom:button-card'
                color_type: icon
                icon: 'mdi:light-switch'
                name: Light
                entity: switch.sonoff_1000cbcad9_2
                tap_action:
                  action: toggle
              - type: 'custom:button-card'
                color_type: icon
                icon: 'mdi:fan'
                name: Fan
                entity: switch.sonoff_1000cbcad9_1
                tap_action:
                  action: toggle
              - type: 'custom:button-card'
                color_type: blank-card
        type: vertical-stack
type: vertical-stack
```

![Screen Shot 2021-05-15 at 3 12 44 PM](https://user-images.githubusercontent.com/15801696/118353368-18beaf00-b590-11eb-937e-1ce9fdca6153.png)

![Screen Shot 2021-05-15 at 3 12 58 PM](https://user-images.githubusercontent.com/15801696/118353371-1e1bf980-b590-11eb-9acc-323d72072ff6.png)
