### ISSUE TITLE
Sonoff L1 not changing color in scenes

### ISSUE THREAD

**Issue by Zip753** [AlexxIT/SonoffLAN#513]
Hi, I'm new to Home Assistant and I'm trying to migrate scenes from SmartThings. I have a Sonoff L1 LED strip which I have successfully connected to Home Assistant via your integration, and I'm trying to add it to scenes. The problem is that when I'm activating the scene, all the other lights are switching colors to the ones configured in the scene, however Sonoff L1 strip just turns on to the last color that it had.

Here's an example of such scene (`light.sonoff_living_room_bookshelf_led_strip` is the entity for L1):
```yaml
- id: '1621584204609'
  name: Nordic vibes
  entities:
    switch.evening_lights_outlet:
      friendly_name: Evening lights outlet
      state: 'on'
    light.yeelight2_kitchen_table_light:
      min_mireds: 153
      max_mireds: 588
      effect_list:
      - Strobe color
      - Police
      - Christmas
      - RGB
      - Random Loop
      - Fast Random Loop
      - LSD
      - Slowdown
      - Night Mode
      - Date Night
      - Movie
      - Sunrise
      - Sunset
      - Romance
      - Happy Birthday
      - Disco
      - Strobe epilepsy!
      - Alarm
      - Police2
      - WhatsApp
      - Facebook
      - Twitter
      - Home
      - Candle Flicker
      - Slow Temp
      - Stop
      supported_color_modes:
      - color_temp
      - hs
      color_mode: hs
      brightness: 128
      hs_color:
      - 267.765
      - 100
      rgb_color:
      - 118
      - 0
      - 255
      xy_color:
      - 0.207
      - 0.072
      color_temp: 153
      flowing: false
      music_mode: false
      friendly_name: Kitchen table light
      supported_features: 63
      state: 'on'
    light.yeelight2_living_room_light:
      min_mireds: 153
      max_mireds: 588
      effect_list:
      - Strobe color
      - Police
      - Christmas
      - RGB
      - Random Loop
      - Fast Random Loop
      - LSD
      - Slowdown
      - Night Mode
      - Date Night
      - Movie
      - Sunrise
      - Sunset
      - Romance
      - Happy Birthday
      - Disco
      - Strobe epilepsy!
      - Alarm
      - Police2
      - WhatsApp
      - Facebook
      - Twitter
      - Home
      - Candle Flicker
      - Slow Temp
      - Stop
      supported_color_modes:
      - color_temp
      - hs
      color_mode: hs
      brightness: 128
      hs_color:
      - 194.062
      - 75.294
      rgb_color:
      - 63
      - 210
      - 255
      xy_color:
      - 0.162
      - 0.271
      color_temp: 588
      flowing: false
      music_mode: false
      friendly_name: Living room light
      supported_features: 63
      state: 'on'
    light.sonoff_living_room_bookshelf_led_strip:
      effect_list:
      - Colorful
      - Colorful Gradient
      - Colorful Breath
      - DIY Gradient
      - DIY Pulse
      - DIY Breath
      - DIY Strobe
      - RGB Gradient
      - DIY Gradient
      - RGB Breath
      - RGB Strobe
      - Music
      supported_color_modes:
      - hs
      color_mode: hs
      brightness: 222
      hs_color:
      - 240
      - 100
      rgb_color:
      - 0
      - 0
      - 255
      xy_color:
      - 0.136
      - 0.04
      effect: Colorful
      manufacturer: SONOFF
      model: L1
      sw_version: PSF-BTA-GL v3.4.0
      cloud: online
      rssi: -45
      friendly_name: Living room bookshelf LED strip
      supported_features: 21
      state: 'on'
```
I have enabled debug logs for `sonoff` and whenever I activate the scene nothing is happening in the logs, meaning that the request is never sent to the device, which explains why the device doesn't react. At the same time, I can see that the icon on the Lovelace dashboard changes to the color that I specified in the scene, so I suspect that the internal state of the entity is indeed updated, however for some reason the actual request to the device never comes through. Just to give you some more context, this is what I see in the logs when I simply toggle the L1 from the Lovelace dashboard:
```
2021-05-22 16:22:49  DEBUG    sonoff_cloud  1000f7e797 => Cloud4 | {'switch': 'on'} | 1621689769143
2021-05-22 16:22:49  DEBUG    sonoff_cloud  1000f7e797 <= Cloud3 | {'error': 0, 'deviceid': '1000f7e797', 'apikey': '...', 'sequence': '1621689769143'}
2021-05-22 16:22:49  DEBUG    sonoff_cloud  1000f7e797 => Cloud5 | Force update sequence: 1621689769319
2021-05-22 16:22:49  DEBUG    sonoff_cloud  1000f7e797 <= Cloud3 | {'error': 0, 'deviceid': '1000f7e797', 'apikey': '...', 'sequence': '1621689769319', 'params': {'bindInfos': {'smartThings': []}, 'version': 8, 'only_device': {'ota': 'success'}, 'sledOnline': 'on', 'ssid': '...', 'bssid': '...', 'switch': 'on', 'light_type': 1, 'colorR': 255, 'colorG': 127, 'colorB': 0, 'bright': 87, 'mode': 1, 'speed': 100, 'sensitive': 1, 'rssi': -45, 'fwVersion': '3.4.0', 'staMac': '...'}}
```

I went to developer tools and attempted to set the state of `light.sonoff_living_room_bookshelf_led_strip` to the exact same state as in `scenes.yaml` (except for the `state: 'on'`), and the same thing happened - I could see in the table below that the state got updated, but the logs were empty and the device didn't change the color.

I have peeked into the source and read some developer docs from Home Assistant, however I haven't found how exactly "set state" updates the entities - I suppose some default behavior from the `light` domain updates the state, however I don't know which code from the platform integration is called at that moment. I have found this in the docs: https://developers.home-assistant.io/docs/reproduce_state_index/ Maybe this is something that will have to be implemented in order to send the request to the device upon activating a scene?

---

Some more technical details:
- I have only installed Sonoff LAN via HACS and don't have any other Sonoff integration
- SonoffLAN version - 2.4.6
- only configured username and password in the sonoff config, so running in the default cloud + local mode
- L1 is only registered as an entity, no device for it is available (so e.g. in the scene I'm adding it as an entity, unlike other bulbs which I add as devices)
- all L1 details should be visible in the entity definition in the scene above
- also pasting default HA stats below

## System Health

version | core-2021.5.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.9
os_name | Linux
os_version | 5.4.83-v8
arch | aarch64
timezone | Europe/Tallinn

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4995
Installed Version | 1.12.3
Stage | running
Available Repositories | 822
Installed Repositories | 4

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | June 18, 2021, 3:00 AM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 5.13
-- | --
update_channel | stable
supervisor_version | supervisor-2021.04.3
docker_version | 19.03.15
disk_total | 28.6 GB
disk_used | 3.2 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Visual Studio Code (3.4.0), File editor (5.3.0), Home Assistant Google Drive Backup (0.104.3)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 0
mode | auto-gen

</details>
