### ISSUE TITLE
RF Bridge Issues

### ISSUE THREAD

**Issue by iotinkognito** [AlexxIT/SonoffLAN#535]
Hi, I have enabled SonoffLan with the following code.

sonoff:
  username: user@domain.com
  password: "password"
  reload: always # update device list every time HA starts

In all examples I have see it shows there should be the most recent button press state / button name and utc time. I don't see any attributes than the following screen shot.
![image](https://user-images.githubusercontent.com/82223761/124146436-56d04d80-dac0-11eb-947f-90c50f0dacda.png)

To trouble shoot of have removed the linkage to configuration.yaml, removed entities, restarted numerous times. I have also shared my devices to a secondary account and renabled in HA config. 

I have tried to setup the sensors also 
```
sonoff:
  username: user@domain.com
  password: "password"
  reload: always # update device list every time HA starts
  rfbridge:
    FrontDoorOpen:  # button name in eWeLink application (open signal)
      name: FrontDoorOpenNew   # optional, you can change sensor name
      device_class: window  # e.g. door, window
      timeout: 0  # disable auto close timeout
      payload_off: FrontDoorCloseNew  # button name in eWeLink application (close signal)
```

or even a persistent notification automation and get nothing at all, no errors etc.
