### ISSUE TITLE
HA builtin energy usage

### ISSUE THREAD

**Issue by guciopl** [AlexxIT/SonoffLAN#562]
Hi,
With HA 2021.8 they implemented energy usage tools, but I cannot link usage from my sonoff POWs devices as they dont appear on the list. In help there is tip to inform integration author about this: https://developers.home-assistant.io/docs/core/entity/sensor#long-term-statistics
Is there anything You can do here?

**Comment by johnjoemorgan** [comment]
I can confirm the same with a S31.  I have one unit flashed with Tasmota that is reporting the power data to the Energy integration and on with Sonoff firmware that is not.

 I know that in of itself is of little help but please let me know what information or set up/configs you may want me to test out.

My timezone is GMT-8

**Comment by yousaf465** [comment]
I am also looking for the same. Monitor energy usage using sonoff firmware.

**Comment by smartDev22** [comment]
https://aliexpress.ru/item/4001119010843.html
I have such a relay, it does not have a built-in calculation of the consumed energy, how can I get this data from this device? Mb there is some description of api from ewelink?

**Comment by johnjoemorgan** [comment]
@yousaf465 @smartDev22 

You need to create a sensor in HA via a template.

In your sensor.yaml create the sensor from the Sonoff device:

  - platform: integration
    source: sensor.sonoff_10003cc37b_power
    name: IT Power Manual
    unit_prefix: k
    unit: kWh
    round: 2

That creates a kWh sensor you can either place into the UI as usual and/or the new Energy dashboard.

Devices such as these Sonoff's maybe updated via firmware updates later to show the information to HA in the way HA wants but it's unlikely

![image 1](https://user-images.githubusercontent.com/45795798/128969269-e92e7784-a183-4664-ba77-9c2d346946e7.jpg)
![image 2](https://user-images.githubusercontent.com/45795798/128969296-bd67e38e-9b83-4c1b-b945-dd0cba8b1345.jpg)


Additionally, if your device only gives the Watts or Load Power or Power as an **_attribute_** then you can use this code in sensor.yaml to make that attribute into a sensor for Watts/Power then then use the code above.

  - platform: template
    sensors:
      water_filter_watts:
        device_class: power
        unit_of_measurement: 'W'
        friendly_name: 'Water Filter Watts'
        value_template: "{{ states.switch.xiaomi_miio_switch.attributes.load_power }}"

**Comment by guciopl** [comment]
@johnjoemorgan  
I have done what You wrote:

```
sensor:
- platform: integration
  source: sensor.sonoff_10007c87fb_power
  name: Dishwasher
  unit_prefix: k
  unit: kWh
  round: 2

- platform: template
  sensors:
    power_dishwasher:
      friendly_name: DIshwasher
      unit_of_measurement: W
      device_class: power
      value_template: "{{ state_attr('switch.sonoff_10007c87fb', 'power') }}"
```

and still no statistics available in step 3 of energy dashboard.
![ha](https://user-images.githubusercontent.com/61185430/128999568-39cfccb8-4f3c-46de-89f9-054af6a42d3c.PNG)

**Comment by Gferretta** [comment]
> @johnjoemorgan  
> I have done what You wrote:
> 
> ```
> sensor:
> - platform: integration
>   source: sensor.sonoff_10007c87fb_power
>   name: Dishwasher
>   unit_prefix: k
>   unit: kWh
>   round: 2
> 
> - platform: template
>   sensors:
>     power_dishwasher:
>       friendly_name: Dishwasher
>       unit_of_measurement: W
>       device_class: power
>       value_template: "{{ state_attr('switch.sonoff_10007c87fb', 'power') }}"
> ```
> 
> and still no statistics available in step 3 of energy dashboard.
> ![ha](https://user-images.githubusercontent.com/61185430/128999568-39cfccb8-4f3c-46de-89f9-054af6a42d3c.PNG)
> 

Add:
state_class: measurement

**Comment by johnjoemorgan** [comment]
@Gferretta it can take up to an hour for data

End of the day here fir me (UTC-8) Will compare you code asap

**Comment by guciopl** [comment]
Added       state_class: measurement

```
sensor:
- platform: integration
  source: sensor.sonoff_10007c87fb_power
  name: Dishwasher
  unit_prefix: k
  unit: kWh
  round: 2

- platform: template
  sensors:
    power_dishwasher:
      friendly_name: Dishwasher
      unit_of_measurement: W
      device_class: power
      state_class: measurement
      value_template: "{{ state_attr('switch.sonoff_10007c87fb', 'power') }}"

```

Now in HA > Settings > Server configuration > Check configuration I have:
Invalid config for [sensor.template]: [state_class] is an invalid option for [sensor.template]. Check: sensor.template->sensors->power_pralka->state_class. (See ?, line ?).
