### ISSUE TITLE
False positives in HA with Sonoff RF bridge

### ISSUE THREAD

**Issue by sparcopt** [AlexxIT/SonoffLAN#581]
Hello, 
Thank you for the amazing work on this integration. 

I'm using 1 Sonoff RF bridge with 1 DW2-RF as a mailbox sensor.

This is my HA config:
```yaml
sonoff:
  username: XXX
  password: XXX
  rfbridge:
    Mailbox sensor:
      device_class: door
      timeout: 5
```

Everything has been working as intended. I open the mailbox and HA sensor goes from `closed` to `open`.

However, I'm also getting false positives from time to time. The HA sensor reports `open` when it wasn't opened.
The eWeLink alarm history doesn't show anything, which confirms the sensor wasn't physically triggered.

Screenshot from HA history:
![image](https://user-images.githubusercontent.com/20686451/130460487-edd04fbe-98e3-44df-a44f-ed244750e219.png)

Screenshot from eWeLink history:
![image](https://user-images.githubusercontent.com/20686451/130461349-4842f5dc-069a-422c-ba95-dd6584e8598b.png)

If you need more info let me know.
