### ISSUE TITLE
Sonoff TH16: temperature unknown

### ISSUE THREAD

**Issue by booroondookZ** [AlexxIT/SonoffLAN#590]
My config:
```
sonoff:
  scan_interval: '00:05:00'
  force_update: temperature
  sensors: temperature
  username: bla-bla-bla@gmail.com
  password: mysuperpassword
  mode: local
  reload: always
  devices:
    100XXXXXXX:
      name: Sonoff TH16
      force_update: True
```
Home Assistant always shows "unknown" value for sensor.sonoff_100XXXXXXX_temperature 
![2021-09-05 11_30_49-Window](https://user-images.githubusercontent.com/8210458/132120643-8fa31cd0-bb86-4933-976b-3685e58ca9ad.png)

**Comment by sunhort** [comment]
I've been having same trouble before changing it to currentHumidity, currentTemperature as found in sonoff.json

**Comment by booroondookZ** [comment]
> I've been having same trouble before changing it to currentHumidity, currentTemperature as found in sonoff.json

Please tell detailed where you made your changes.

**Comment by sunhort** [comment]
sure,bro,
```
sonoff:
  username: blaa
  password: blabla
  force_update: [currentTemperature, currentHumidity, voltage_00]
  scan_interval: '00:05:00'  # (optional) default 5 minutes
  sensors: [currentTemperature, currentHumidity, voltage_00, rssi]
  reload: always
  mode: local
```
after in device section:
```
devices:
    1xxxxxxxx:
      device_class: switch
      name: Sonoff TH10 
      devicekey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      sensors: [currentTemperature, currentHumidity, rssi]
```
after that it works fine even in local mode which makes me happy )
For TH16 double check name in sonoff.json, but I bet it will be the same
