### ISSUE TITLE
device_class makes the device unavailable in HA

### ISSUE THREAD

**Issue by booroondookZ** [AlexxIT/SonoffLAN#595]
My config:
```
sonoff:
  username: xxxxxxx@xxxxxx.xxx
  password: xxxxxxxx
  mode: local
  reload: always
  devices:
    10xxxxxx24: #Sonoff Basic R2
      name: Movable outlet
    10xxxxxx78: #Sonoff Mini
      name: Lamps in the Lobby
      device_class: light
    10xxxxxx4a: #Sonoff Basic R2
      name: Spotlight in the yard
      device_class: light
    10xxxxxx49: #Sonoff TH16
      name: Outlet in the Garage
```
If I specify "device_class" for a device, then this device will become unavailable in Home Assistant.
If I delete the "device_class", the device becomes available again.
What am I doing wrong?
