### ISSUE TITLE
I get TH16 temp updates even without force_update - is that right?

### ISSUE THREAD

**Issue by sddgit** [AlexxIT/SonoffLAN#600]
As the title says, even without specifying force_update, my TH16 temperature sensor updates pretty quickly (within 10-15 seconds). I assumed I would need force_update for this to happen. Am I missing something? Config:

```
sonoff:
  username: !secret sonoff_username
  password: !secret sonoff_password
  #force_update: temperature
  #scan_interval: '00:00:30'
  sensors: temperature
```
And thank you for this amazing integration. It’s enabled me to get a long way with automating the operation of my pool.
