### ISSUE TITLE
POWR2 with FW 3.5 is reporting Voltage and Current as device class power

### ISSUE THREAD

**Issue by Fox350** [AlexxIT/SonoffLAN#612]
Hy Alex and thanks so much for your work.

Here is my configuration 
```
sonoff:
  username: !secret sonoffemail
  password: !secret sonoffpassword
  force_update: [temperature, power]
  scan_interval: '00:05:00'  # (optional) default 5 minutes
  sensors: [temperature, humidity, power, current, voltage, rssi]
```

All is working great but since the Energy development tool arrived I realized that those device class are Power instead of Voltage and Current so they trigger an error in the statistic development tools.

Here is the error message : 
The unit of your entity is not a supported unit for the device class of the entity, power.
Statistics can not be generated until this entity has a supported unit.

If this unit was provided by an integration, this is a bug. Please report an issue.

If you have set this unit yourself, and want to have statistics generated, make sure the unit matches the device class. The supported units are documented in the developer documentation.

This is trigerred for the _current and _voltage sensor.

I was able to change the device class in personalisation for voltage and current.  It did not clear the error right after the reboot but it did during the next day.

Thanks
