### ISSUE TITLE
Unusable Sonoff Pow R2 - Refresh rate SPAM

### ISSUE THREAD

**Issue by brokuene** [AlexxIT/SonoffLAN#635]
When I added Sonoff POW R2 using this integration the POWER sensor works fine in HA but the issue is that it doesn't respect 'scan_interval' property. 

Now the POWER sensor refreshes every 2-3 seconds making HA db huge. 
Tried multiple different configurations and cannot get rid of the issue.

```
sonoff:
  username: !secret sonoff_user
  password: !secret sonoff_cloud_password
  mode: local
  force_update: [power]
  scan_interval: '00:05:00' # (optional) default 5 minutes
  sensors: [power]
```

or

```
sonoff:
  username: !secret sonoff_user
  password: !secret sonoff_cloud_password
  # debug: True
  mode: local
  reload: always
  # force_update: [power] 
  scan_interval: 00:05:00  # (optional) default 5 minutes
  sensors: [power]  # !!! SonoffLAN v2.1+
  devices:
    10009ed555:
      name: Socket1
      force_update: True
```

I also tried `mode: cloud`.

Firmware name: PSC-B67-GL
Application version: 3.5
EWeLink: V 4.17.1

This forces me to disable sonoff as it would harm my HA :( 
This looks similar a little bit to issue #272
