### ISSUE TITLE
Problem with conditions in automations - sonoff.remote event  - bridge 433RF

### ISSUE THREAD

**Issue by lucamargoni** [AlexxIT/SonoffLAN#654]
Randomly, the attribute 'name' is not recognized and the automations start bypassing the conditions.
**Problem start with HA 2021.12** 
Config: mode: local -  reload: always

thanks for your help
```
alias: ALLARME INCENDIO
description: ''
trigger:
  - platform: event
    event_type: sonoff.remote
condition:
  - condition: not
    conditions:
      - condition: state
        entity_id: remote.sonoff_1000e738f6
        state: Aspirazione centralizzata
        attribute: name
  - condition: not
    conditions:
      - condition: state
        entity_id: remote.sonoff_1000e738f6
        state: Pompa giardino
        attribute: name
action:
  - service: notify.mobile_app_iphone_di_luca
    data:
      title: ALLARME INCENDIO
      message: 'Name: {{ trigger.event.data.name }}'
      data:
        push:
          sound:
            name: Update.caf
            critical: 1
            volume: 0.9
```

![traccia automazione incendio](https://user-images.githubusercontent.com/73077028/146040260-3ac9ef4e-62f0-4cdf-9b71-a61ce2e3718f.png)
![log](https://user-images.githubusercontent.com/73077028/146040261-e122660c-ada4-43c2-a4ab-9610206af370.png)
