### ISSUE TITLE
Couldn't see devices

### ISSUE THREAD

**Issue by Chamvrn** [AlexxIT/SonoffLAN#667]
I've installed the SonoffLAN add-on, devices appeared in the "Developer tools" but not in the Devices when creating automation.
Here are some strings from the configuration.yaml
```
sonoff:
    username: MyLogin
    password: MyPassword
    reload: always
    devices:
        switch.sonoff_10007b86a8_1:
          device_class:
            - light  # zone 1 (channel 1)
            - light  # zone 2 (channel 2)
          name: Sonoff 2CH Pow
```
What I'm missing? Thanks in advance.
