### ISSUE TITLE
Temperature being reported as Celsius 

### ISSUE THREAD

**Issue by Zipties** [AlexxIT/SonoffLAN#718]
I have a TH16 which I have configured to report in Fahrenheit on the ewelink app, but it reports celsius to Home Assistant, and there isn't a unit of measurement attribute. 

![CleanShot 2022-02-25 at 11 53 27@2x](https://user-images.githubusercontent.com/11506166/155763566-2f1ed5d7-24f7-432a-a1c0-7e58358cc3e3.jpg)

```
sonoff:
  username: email
  password: password
  mode: local
  force_update: [currentTemperature, currentHumidity, voltage_00]
  scan_interval: '00:01:00'  # (optional) default 5 minutes
  sensors: [currentTemperature, currentHumidity, voltage_00, rssi]
```

I found this in sensors.py and tried changing it to °F but it didn't change anything. I also tried adding "currentTemperture" but that made the state go unavailable. 

```
SENSORS = {
    'temperature': [DEVICE_CLASS_TEMPERATURE, '°C', None],
    # UNIT_PERCENTAGE is not on old versions
    'humidity': [DEVICE_CLASS_HUMIDITY, '%', None],
    'dusty': [None, None, 'mdi:cloud'],
    'light': [DEVICE_CLASS_ILLUMINANCE, None, None],
    'noise': [None, None, 'mdi:bell-ring'],
    'power': [DEVICE_CLASS_POWER, 'W', None],
    'current': [DEVICE_CLASS_POWER, 'A', None],
    'voltage': [DEVICE_CLASS_POWER, 'V', None],
    'rssi': [DEVICE_CLASS_SIGNAL_STRENGTH, 'dBm', None]

}
```

Can this be changed within SonoffLAN or do I need to create a template sensor to convert it?

**Comment by nrdeworks** [comment]
Same issue. Tried with the eWeLink too and it passes 'C' not 'F' into HA. Running HassIO.

**Comment by nrdeworks** [comment]
Were you able to solve this?

**Comment by Zipties** [comment]
I just ended up doing a template sensor...several actually. I needed to do a compensation filter to calibrate it, one to convert it to Fahrenheit, and another to add % to the humidity sensor.

**Comment by Zipties** [comment]
Here is mine 

```
 - platform: template
   sensors:
     sonoff_outdoor_temperture_f:
       unique_id: 74877 
       friendly_name: "Sonoff Outdoor Temp F"
       unit_of_measurement: '°F'
       value_template: >-
         {% set t = states('sensor.compensation_sensor_sonoff_10015dca5f_currenttemperature') | float %}
         {{((t)*9/5)+32}}
```
