### ISSUE TITLE
TH10 in Local only mode - not reporting humidity

### ISSUE THREAD

**Issue by loveisfoss** [AlexxIT/SonoffLAN#753]
As the title says, I get only an entity that behaves like a switch. The sonoff device is in an isolated IoT VLAN that does not have access to the internet but can be accessed by home-assistant (which has access to the internet - is connected to an internet capable VLAN).

config.yaml
```
sonoff:
  devices:
     xxxxxxxxxx:
        devicekey: xxxxxx
        name: xxxxxxx
```
If I add `sensors: [humidity] ` after `name:` nothing happens.
If I add it before the `devices:`, home assistant enters recovery mode.

Am I missing something or is it a non implemented function?
