### ISSUE TITLE
iFan03 light entity unavailable

### ISSUE THREAD

**Issue by HenryJoe666** [AlexxIT/SonoffLAN#755]
after installing 2.4.7 ifan03 fan entity was fixed, but light entity became unavailable constantly.
i removed my configuration to basic (only username and password) and could control ifan light and fan entities but other sonoff entities became unavailable (ie. sonoff mini switches). if i comment all other entities and leave only ifan light it works again but looses sonoff mini entities (they become unavailable as before) i can use this light normally from ewelink app.
my config:
```
sonoff:
  username: mymail
  password: mypassword
  reload: always
  mode: cloud
  devices:
    1000338ffe:
      device_class: light
      name: Sanca
    1000ab934b:
      device_class: light
      name: Varanda
    1000ac0449:
      device_class: light
      name: Estante
    1000b6f482:
      device_class: light
      name: Escada
    1000b72f4c:
      device_class: light
      name: Corredor
    1000995098:
      device_class: fan
      name: Ventilador
    1000995098_1:  # this is the problematic light from ifan03, with the above code this light never works
      device_class: light
      name: Ventilador
```
