### ISSUE TITLE
Sonoff Dual R2

### ISSUE THREAD

**Issue by leopold005** [AlexxIT/SonoffLAN#76]
First of all, you can pretty much add the Dual R2 to the list of devices that work!  I've got one of these and your integration picks it up and it works, so that's a good thing.

However, it appears I can't use the "device class" to differentiate between the two switches in the unit, it seems to just default to "switch" (unless I set the default class, in which case they both report as that instead).  It's not a massive issue for me as they are both technically switches and I can work around it, but I thought you should know about it.

For info, the entity IDs for these is as follows:
`{class}.sonoff_{device ID}_{switch number}`
Where {switch number} is 1 or 2, for the two switches.

**Comment by AlexxIT** [comment]
Hi. I do not understand what problem are you trying to solve.

**Comment by leopold005** [comment]
I wanted to specify the device class as your instructions say are possible.  In my specific configuration, one of the switches operates a light and the other is connected to a plug socket.  I was hoping the device class would be able to make this distinction, but it doesn't appear to work and just sets both switches to whatever device class it comes across first.  Like I said, it's not a massive issue for me, but I just thought it might be something you may want to investigate when you have some time.

**Comment by AlexxIT** [comment]
Try this:
```
    1000abcde2:
      device_class: [light, switch]
```

**Comment by leopold005** [comment]
I tried that, it didn't work

**Comment by AlexxIT** [comment]
It should work. Show your config, hide private data.

**Comment by leopold005** [comment]
Okay, this is what I have in my config:

```
sonoff:
  username: !secret myusername
  password: !secret mypassword
  reload: always
  1000a8bf27:  # Sonoff Dual in shed
    device_class: [light, switch]
```

**Comment by AlexxIT** [comment]
```yaml
sonoff:
  username: !secret myusername
  password: !secret mypassword
  reload: always
  devices:
    1000a8bf27:  # Sonoff Dual in shed
      device_class: [light, switch]
```
