### ISSUE TITLE
Allow entity id customization

### ISSUE THREAD

**Issue by iromeo** [AlexxIT/SonoffLAN#82]
I'm using Sonoff Mini w/o DYI mode, I manage to change entity name using `name` property, but I also prefer to get human readable entity ids, e.g. not `light.sonoff_1000cxxxxxx` but `light.sonoff_bathroom`. 

So for
```
sonoff:
  devices:
    !secret sonoff_mini_1_did:
      name: "Sonoff Bathroom"  # or "sonoff_bathroom"
      devicekey: !secret sonoff_mini_1_apikey
      device_class: light
```
I'd like to get `light.sonoff_bathroom` sensor, similar to many other integrations.

Maybe it's more convenient to have a config like:
```
sonoff:
  devices:
    sonoff_bathroom:
      # name: "Sonoff Bathroom Light" # Optional
      deviceid: !secret sonoff_mini_1_did
      devicekey: !secret sonoff_mini_1_apikey
      device_class: light
```
