### ISSUE TITLE
Error cannot import BinarySensorDeviceClass

### ISSUE THREAD

**Issue by Fernando-A-Rocha** [AlexxIT/SonoffLAN#838]
Hello, I have Home Assistant 2021.11.5

Today I reinstalled the Sonoff integration with HACS, and when adding my config to the configuration.yaml and checking it, HA gives an error.

my config:
```yaml
sonoff:
  username: !secret sonoffs_user
  password: !secret sonoffs_pw

  # specific Pow/TH
  force_update: [temperature, power]
  scan_interval: "00:05:00" # (optional) default 5 minutes
  sensors: [temperature, humidity, power, current, voltage]
```

error:
> Component error: sonoff - cannot import name 'BinarySensorDeviceClass' from 'homeassistant.components.binary_sensor' (/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py)

help?
