### ISSUE TITLE
update_entity not working for/with THR316D

### ISSUE THREAD

**Issue by Masterz69** [AlexxIT/SonoffLAN#943]
HA OS 8.4, HA Core 2022.8.1, Sonoff 3.1.0.

Added THR316D to my environment.
Created automation a described in README.md:
```
- id: sonoff_update_th
  alias: Sonoff update TH
  trigger:
    - platform: time_pattern
      minutes: "/1"
  action:
    - service: homeassistant.update_entity
      target:
        entity_id: switch.sth_test
```

Automation fires every minute, executes, no errors/messages in Core log, all looks fine.
But no new data in HA appears in temperature & humidity entities.

Automation trace: 
[trace automation.sonoff_update_th 2022-08-05T19_07_00.004702+00_00.json.zip](https://github.com/AlexxIT/SonoffLAN/files/9271080/trace.automation.sonoff_update_th.2022-08-05T19_07_00.004702%2B00_00.json.zip)

Device diag: 
[sonoff-a0656de0df0bb579aa4ece0459ab70e2-sTH OverHang-a9d3a7d4bf9eb492b9dbe427bfb4f40c.json.txt](https://github.com/AlexxIT/SonoffLAN/files/9271085/sonoff-a0656de0df0bb579aa4ece0459ab70e2-sTH.OverHang-a9d3a7d4bf9eb492b9dbe427bfb4f40c.json.txt)

Integration debug not available - #936.

Something similar see in #941 - POWR2 have on updates on same service.
